const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function mixed(a){for(let n=0;n<30;n++){const b=shuffle(a);if(b.every((x,i)=>x!==a[i]))return b}return [...a.slice(1),a[0]]}
function speak(text){if(!('speechSynthesis'in window)){ $('#feedback').textContent='Voorlezen is niet beschikbaar in deze browser.';return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-BE';u.rate=.82;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='nl-BE')||voices.find(v=>v.lang.startsWith('nl'))||null;speechSynthesis.speak(u)}
function view(id){window.speechSynthesis?.cancel();['home','game','vocabulary'].forEach(x=>$('#'+x).hidden=x!==id);$('#back').hidden=id==='home';$('#themes').hidden=id!=='home';scrollTo(0,0)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-say]');if(b)speak(b.dataset.say)});$('#back').onclick=()=>view('home');
function gamePicture(g,l){return g.items?.find(o=>o.image)?.image||g.pairs?.find(p=>p.left.image)?.left.image||g.questions?.find(q=>q.image)?.image||g.questions?.flatMap(q=>q.options).find(o=>o.image)?.image||'assets/eigen/archeoloog.png'}
let lessonQueue=[],activeLesson=null;
const menu=$('#menu');menu.className='lesson-tiles';TIME_CONTENT.lessons.forEach(l=>{const row=document.createElement('div');row.className='menu-option';row.innerHTML=`<button class="start"><img class="menu-picture" src="${gamePicture(l.games[0],l)}" alt=""><strong>Les ${l.n} · ${esc(l.title)}</strong><span>Oefen de hele les →</span></button><button data-say="${esc('Les '+l.n+'. '+l.title+'. Oefen de hele les.')}" aria-label="Lees deze les voor">🔊</button>`;row.querySelector('.start').onclick=()=>{activeLesson=l;lessonQueue=l.games.slice(1);start(l.games[0],l)};menu.append(row)});
$('#words').onclick=()=>location.href='woorden-oefenen.html';

let game,index=0,locked=false,selected=null,found=new Set(),order=[];
function start(g,l){game=g;index=0;$('#gameTitle').textContent=`Les ${l.n} · ${g.title}`;view('game');render()}
function visual(o){return `${o.image?`<img src="${o.image}" alt="">`:''}${o.text?`<span>${esc(o.text)}</span>`:''}`}
function option(o,i,side='answer'){const word=o.text||`prent ${i+1}`;return `<div class="option"><button class="pick ${timeWordClass(o.text)}" data-side="${side}" data-index="${i}" aria-label="${esc(word)}">${visual(o)}</button><button class="listen" data-say="${esc(word)}" aria-label="Lees ${esc(word)} voor">🔊</button></div>`}
function message(text){$('#feedback').textContent=text;speak(text)}
function render(){locked=false;selected=null;found=new Set();order=[];$('#feedback').textContent='';$('#next').hidden=true;$('#undo').hidden=true;$('#play').className=game.type;$('#progress').textContent=game.type==='choice'?`${index+1} / ${game.questions.length}`:'';
 const instruction=game.type==='choice'?game.questions[index].text:game.instruction;$('#instruction').textContent=instruction;$('#readInstruction').onclick=()=>speak(instruction);
 if(game.type==='choice')renderChoice();else if(game.type==='sequence')renderSequence();else renderMatch();speak(instruction)
}
function renderChoice(){const q=game.questions[index],opts=mixed(q.options.map((o,i)=>({...o,correct:i===0})));$('#play').innerHTML=`${q.image?`<img class="question-image" src="${q.image}" alt="Prent bij de vraag">`:''}<div class="answers">${opts.map((o,i)=>option(o,i)).join('')}</div>`;$('#play').querySelectorAll('.pick').forEach(b=>b.onclick=()=>{if(locked)return;const correct=opts[+b.dataset.index].correct;b.classList.toggle('wrong',!correct);if(correct){locked=true;b.classList.add('correct');b.insertAdjacentHTML('beforeend','<b class="mark">✓</b>');message('Goed zo!');$('#next').hidden=false}else message('Nog niet. Luister nog eens en probeer opnieuw.')})}
function renderSequence(){const items=mixed(game.items.map((o,i)=>({...o,position:i})));$('#play').innerHTML=`<div class="sequence-grid">${items.map((o,i)=>option(o,i)).join('')}</div><p class="sequence-help">Tik eerst op wat het eerst komt. Dan op wat daarna komt.</p>`;$('#undo').hidden=false;$('#undo').onclick=render;$('#play').querySelectorAll('.pick').forEach(b=>b.onclick=()=>{if(b.disabled)return;const o=items[+b.dataset.index];if(o.position!==order.length){b.classList.add('wrong');message('Wat komt er eerst? Probeer nog eens.');return}order.push(o);b.disabled=true;b.classList.remove('wrong');b.classList.add('correct');b.insertAdjacentHTML('beforeend',`<b class="order-number">${order.length}</b>`);if(order.length===items.length){message('Alles staat in de juiste volgorde!');$('#next').hidden=false}else message('Goed! Wat komt daarna?')})}
function renderMatch(){const right=mixed(game.pairs.map((p,i)=>({...p.right,id:i})));$('#play').innerHTML=`<div class="match-column">${game.pairs.map((p,i)=>option(p.left,i,'left')).join('')}</div><div class="match-column">${right.map((o,i)=>option(o,i,'right')).join('')}</div>`;
 $('#play').querySelectorAll('.pick').forEach(b=>b.onclick=()=>{const i=+b.dataset.index;if(b.disabled)return;if(b.dataset.side==='left'){selected=i;$('#play').querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');return}if(selected===null){message('Tik eerst op een kaart links.');return}if(right[i].id!==selected){b.classList.add('wrong');message('Deze horen niet samen. Probeer nog eens.');return}const left=$(`#play [data-side="left"][data-index="${selected}"]`);[left,b].forEach(x=>{x.disabled=true;x.classList.remove('selected','wrong');x.classList.add('correct');x.insertAdjacentHTML('beforeend','<b class="mark">✓</b>')});found.add(selected);selected=null;if(found.size===game.pairs.length){message('Je hebt alles goed verbonden!');$('#next').hidden=false}else message('Goed verbonden! Zoek het volgende paar.')})
}
$('#next').onclick=()=>{if(game.type==='choice'&&index<game.questions.length-1){index++;render()}else if(lessonQueue.length){start(lessonQueue.shift(),activeLesson)}else{view('home');speak('Goed geoefend! Je les is klaar. Kies een andere les.')}};
