(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function derange(a){for(let i=0;i<30;i++){const b=shuffle(a);if(b.every((x,j)=>x!==a[j]))return b}return [...a.slice(1),a[0]]}
const button=document.createElement('button');button.dataset.view='homework';button.textContent='📄 Huistaak maken';document.querySelector('.material-menu').append(button);
const paper=document.createElement('section');paper.id='t3Paper';document.body.append(paper);let ready=Promise.resolve();
button.onclick=()=>{document.body.dataset.view='homework';delete document.body.dataset.print;document.querySelectorAll('.material-menu button').forEach(b=>b.classList.toggle('active',b===button));intro.textContent='Kies oefeningen per les. Vooral kijken, verbinden, omcirkelen en nummeren.';
 tool.innerHTML=`<section class="t3-builder"><h2>Huistaak samenstellen</h2><div class="t3-fields"><label>Titel <select id="hwTitle"><option>Huistaak</option><option>Ik oefen</option><option>Ik herhaal</option></select></label><label>Nummer <input id="hwNumber" type="number" min="1" max="30" value="1"></label><label><input id="hwNumberShow" type="checkbox" checked> Nummer tonen</label></div>${TIME_CONTENT.lessons.map(l=>`<fieldset><legend>Les ${l.n} · ${esc(l.title)}</legend><label><input type="checkbox" data-all="${l.n}"> Hele les selecteren</label>${l.games.map(g=>`<label><input type="checkbox" data-lesson="${l.n}" value="${g.id}"> ${esc(g.title)}</label>`).join('')}${l.n===2?'<label class="dayline-option"><input id="hwDayline" type="checkbox"> Daglijn met prenten bovenaan toevoegen <small>Hulpmiddel: de weekdagen en eergisteren, gisteren, vandaag, morgen en overmorgen.</small></label>':''}${l.n===4?'<label><input type="checkbox" data-lesson="4" value="tekenen"> Teken jezelf en je familie</label>':''}</fieldset>`).join('')}<label><input id="hwSolutions" type="checkbox"> Apart oplossingenblad toevoegen</label><div class="t3-actions"><button id="hwPreview">Voorbeeld vernieuwen</button><button id="hwPrint">Maak PDF / print</button></div><p id="hwStatus" role="status"></p></section>`;
 tool.querySelectorAll('[data-all]').forEach(b=>b.onchange=()=>{tool.querySelectorAll(`[data-lesson="${b.dataset.all}"]`).forEach(x=>x.checked=b.checked);generate()});tool.querySelectorAll('[data-lesson]').forEach(b=>b.onchange=()=>{const xs=[...tool.querySelectorAll(`[data-lesson="${b.dataset.lesson}"]`)],all=tool.querySelector(`[data-all="${b.dataset.lesson}"]`);all.checked=xs.every(x=>x.checked);all.indeterminate=!all.checked&&xs.some(x=>x.checked);generate()});['hwTitle','hwNumber','hwNumberShow','hwSolutions','hwDayline'].forEach(id=>document.getElementById(id).onchange=generate);document.getElementById('hwPreview').onclick=generate;document.getElementById('hwPrint').onclick=async()=>{await ready;if(!paper.children.length){document.getElementById('hwStatus').textContent='Kies eerst een oefening.';return}const ok=await Promise.all([...paper.querySelectorAll('img')].map(i=>i.decode().then(()=>true).catch(()=>false)));if(ok.includes(false)){document.getElementById('hwStatus').textContent='Een afbeelding kon niet laden. Vernieuw het voorbeeld.';return}document.body.dataset.print='t3-homework';window.print()};generate();
};
addEventListener('afterprint',()=>delete document.body.dataset.print);
const picture=o=>`${o.image?`<img src="${o.image}" alt="">`:''}${o.text?`<span>${esc(o.text)}</span>`:''}`;
function matching(pairs,sol){const right=derange(pairs),h=pairs.length*110+10;
 const item=(o,x,y)=>`${o.image?`<image href="${o.image}" x="${x+10}" y="${y+4}" width="210" height="72"/>`:''}<foreignObject x="${x}" y="${y+(o.image?77:21)}" width="230" height="${o.image?30:62}"><div xmlns="http://www.w3.org/1999/xhtml" class="match-label">${esc(o.text)}</div></foreignObject>`;
 return `<svg class="paper-pair-svg" viewBox="0 0 700 ${h}" xmlns="http://www.w3.org/2000/svg">${pairs.map((p,i)=>item(p.left,0,i*110)+`<circle cx="250" cy="${i*110+52}" r="3"/>`).join('')}${right.map((p,i)=>item(p.right,470,i*110)+`<circle cx="450" cy="${i*110+52}" r="3"/>`).join('')}${sol?pairs.map((p,i)=>`<line x1="250" y1="${i*110+52}" x2="450" y2="${right.indexOf(p)*110+52}" stroke="#1975ae" stroke-width="2.5"/>`).join(''):''}</svg>`;
}
function makeExercise(n,title,body,lesson){return `<section class="t3-exercise paper-exercise" data-lesson="Les ${lesson}"><h3 data-task-number="${n}"><span class="exercise-number" style="background:${['#dfa900','#f06452','#218657'][(n-1)%3]}">${n}</span><span class="exercise-instruction">${title}</span></h3><div class="paper-exercise-body">${body}</div></section>`}
function dayline(){return `<aside class="time-dayline" aria-label="Daglijn als hulpmiddel"><h3>Mijn daglijn · dit helpt mij</h3><div class="time-weekdays">${['maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag','zondag'].map(d=>`<span>${d}</span>`).join('')}</div><p class="week-repeat">Na zondag komt weer maandag.</p><div class="time-relative-days">${['eergisteren','gisteren','vandaag','morgen','overmorgen'].map(d=>`<div class="${d==='vandaag'?'today':''}"><img src="assets/${d}.png" alt=""><b>${d}</b></div>`).join('')}</div></aside>`}
function page(title,subtitle,body,sol,withDayline){return `<article class="t3-page t3-bundle ${sol?'t3-solutions':''}"><header class="homework-header">${sol?'':'<div class="homework-meta"><span>Naam: ____________________</span><span>Datum: ____________</span></div>'}<div class="homework-title"><h1>${sol?'Oplossingen':esc(title)}</h1><h2>${esc(subtitle)}</h2><p>Tijd · 1ste leerjaar</p></div>${withDayline?dayline():''}</header>${body}</article>`}
function generate(){const selected=[...tool.querySelectorAll('[data-lesson]:checked')],plans=[];let number=0;const lessonNumbers=[...new Set(selected.map(x=>+x.dataset.lesson))];
 for(const checkbox of selected){const l=TIME_CONTENT.lessons.find(l=>l.n===+checkbox.dataset.lesson),g=l.games.find(g=>g.id===checkbox.value);if(!g){plans.push({n:++number,l,title:'Teken jezelf en je familie.',normal:'<div class="drawing-pair"><div><b>Dit ben ik.</b></div><div><b>Mijn familie</b></div></div>',answer:'<p>Eigen tekening. Elke familie is anders; er is geen vast modelantwoord.</p>'});continue}
 if(g.type==='choice'){for(let i=0;i<g.questions.length;i+=2){const qs=g.questions.slice(i,i+2).map(q=>({...q,choices:shuffle(q.options)}));const render=sol=>qs.map((q,j)=>`<div class="time-paper-question"><b>${String.fromCharCode(97+j)}) ${esc(q.text)}</b>${q.image?`<img class="paper-context" src="${q.image}" alt="">`:''}<div class="paper-answers ${q.choices.some(o=>o.image)?'with-images':''}">${q.choices.map(o=>`<div class="paper-answer"><span class="check-box">${sol&&o===q.options[0]?'×':''}</span>${picture(o)}</div>`).join('')}</div></div>`).join('');plans.push({n:++number,l,title:'Kruis het juiste antwoord aan.',normal:render(false),answer:render(true)})}}
 else if(g.type==='sequence'){const items=derange(g.items);const render=sol=>`<p>${esc(g.title)}. Begin met 1.</p><div class="time-paper-order">${items.map(o=>`<div>${picture(o)}<span class="time-number-box">${sol?g.items.indexOf(o)+1:''}</span></div>`).join('')}</div>`;plans.push({n:++number,l,title:'Nummer de kaarten in de juiste volgorde.',normal:render(false),answer:render(true)})}
 else {const normal=matching(g.pairs,false);const answer=document.createElement('div');answer.innerHTML=normal;const svg=answer.querySelector('svg');const nodes=[...svg.querySelectorAll('foreignObject')].slice(g.pairs.length);g.pairs.forEach((pair,i)=>{const rightIndex=nodes.findIndex(n=>n.textContent===pair.right.text);const line=document.createElementNS('http://www.w3.org/2000/svg','line');Object.entries({x1:250,y1:i*110+52,x2:450,y2:rightIndex*110+52,stroke:'#1975ae','stroke-width':2.5}).forEach(([k,v])=>line.setAttribute(k,v));svg.append(line)});plans.push({n:++number,l,title:'Verbind wat bij elkaar hoort.',normal,answer:answer.innerHTML})}
 }
 const title=document.getElementById('hwTitle').value+(document.getElementById('hwNumberShow').checked?' '+Math.max(1,Math.min(30,+document.getElementById('hwNumber').value||1)):''),subtitle=lessonNumbers.length===1?`Les ${lessonNumbers[0]} – ${TIME_CONTENT.lessons.find(l=>l.n===lessonNumbers[0]).title}`:lessonNumbers.map(n=>'Les '+n).join(', ');
 const body=sol=>{let prev=null;return plans.map(p=>{const heading=lessonNumbers.length>1&&prev!==p.l.n?`<h2 class="t3-lesson-heading">Les ${p.l.n} · ${esc(p.l.title)}</h2>`:'';prev=p.l.n;return heading+makeExercise(p.n,p.title,sol?p.answer:p.normal,p.l.n)}).join('')};
 const withDayline=lessonNumbers.includes(2)&&document.getElementById('hwDayline').checked;
 paper.innerHTML=plans.length?page(title,subtitle,body(false),false,withDayline)+(document.getElementById('hwSolutions').checked?page(title,subtitle,body(true),true,withDayline):''):'';ready=layoutTheme3Homework(paper);document.getElementById('hwStatus').textContent=plans.length?`${plans.length} opdrachten in één huistaak. De nummering loopt door.`:'Kies een oefening om het voorbeeld te bekijken.';
}
})();
