const data=TIME_CONTENT.words.map(w=>[w.word,w.image,w.help,w.kind]);
const THEME='Tijd · 1ste leerjaar',HOME=new URL('./',location.href).href,tool=document.querySelector('#tool'),intro=document.querySelector('#intro');
function cards(){return `<section id="cards">${data.map(([w,img])=>`<article class="card"><img class="photo" src="${img}" alt="${w}"><h2>${w}</h2></article>`).join('')}</section>`}
function question(w,i){const choices=[`Wijs iets aan dat bij “${w}” past.`,`Gebruik “${w}” in een goede zin.`,`Leg in je eigen woorden uit wat “${w}” betekent.`,`Geef een voorbeeld van “${w}”.`];return choices[i%choices.length]}
function strips(){return `<section class="strips">${data.map(([w,,help],i)=>`<article class="strip"><b>${w}</b><span>${question(w,i)}</span><small><strong>Houvast leerkracht:</strong> ${help}</small></article>`).join('')}</section>`}
function wall(){return `<p class="wall-note">Elk kaartje heeft een afbeelding én een korte uitleg. Het te raden woord staat er niet op.</p><section class="wall-grid">${data.map(([w,img,help,kind])=>`<article class="wall-card" data-kind="${kind}"><img src="${img}" alt="Beeld bij ${w}"><div class="wall-description">${help}</div></article>`).join('')}</section>`}
function enableCardPrintChooser(){const cards=[...document.querySelectorAll('#cards .card')];if(!cards.length)return;const bar=document.createElement('div');bar.className='card-print-tools';bar.innerHTML='<button class="choose-cards">☑ Kies wandplaten</button><span class="selection-actions" hidden><button class="choose-all">Alles kiezen</button> <button class="primary print-chosen">🖨️ Print gekozen</button></span>';tool.prepend(bar);cards.forEach((card,i)=>{const label=document.createElement('label');label.className='card-choice';label.innerHTML=`<input type="checkbox" aria-label="Kies wandplaat ${i+1}"> kiezen`;card.prepend(label);label.querySelector('input').onchange=e=>card.classList.toggle('chosen',e.target.checked)});const actions=bar.querySelector('.selection-actions'),choose=bar.querySelector('.choose-cards');choose.onclick=()=>{const active=document.querySelector('#cards').classList.toggle('selecting');actions.hidden=!active;choose.textContent=active?'✕ Stop met kiezen':'☑ Kies wandplaten'};bar.querySelector('.choose-all').onclick=()=>cards.forEach(card=>{card.classList.add('chosen');card.querySelector('input').checked=true});bar.querySelector('.print-chosen').onclick=()=>printCardSelection()}
function printCardSelection(){if(!document.querySelector('#cards .card.chosen')){alert('Vink eerst minstens één wandplaat aan.');return}document.body.dataset.print='card-selection';setTimeout(()=>print(),50)}
addEventListener('afterprint',()=>{delete document.body.dataset.print});
function setup(){return `<section class="qr-setup"><h2>QR-kaartjes voor de kinderen</h2><label>Aantal kinderen <input id="qrCount" type="number" min="1" max="40" value="24"></label><div><button id="makeQr">Maak kaartjes</button><button id="makePoster">Maak één klasposter</button></div></section><section id="qrOutput"></section>`}
function addQr(box,size){new QRCode(box,{text:HOME,width:size,height:size,colorDark:'#6552b8',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M})}
function qrCards(n){document.body.dataset.print='qr-cards';const o=document.querySelector('#qrOutput');o.className='qr-grid';o.innerHTML=Array.from({length:n},(_,i)=>`<article class="qr-card"><h2>Ik oefen</h2><h3>${THEME}</h3><div class="qr-code" id="qr-${i}"></div><p>Scan en oefen mee!</p></article>`).join('');document.querySelectorAll('.qr-code').forEach(x=>addQr(x,105))}
function poster(){document.body.dataset.print='qr-poster';const o=document.querySelector('#qrOutput');o.className='qr-poster-wrap';o.innerHTML=`<article class="qr-poster"><p>ZISA WO SPELEN</p><h1>Ik oefen</h1><h2>${THEME}</h2><div id="posterQr"></div><strong>Scan en oefen mee!</strong></article>`;addQr(document.querySelector('#posterQr'),260)}
function show(v){document.body.dataset.view=v;delete document.body.dataset.print;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='cards'){intro.textContent=`Alle ${data.length} woorden en herkenbare begrippen, met een duidelijke afbeelding.`;tool.innerHTML=cards();enableCardPrintChooser()}else if(v==='strips'){intro.textContent='Eén lange dagstrook per woord, met uitleg als houvast voor de leerkracht.';tool.innerHTML=strips()}else if(v==='wall'){intro.textContent='Kaartjes van 6,2 × 7,8 cm: afbeelding en uitleg, zonder het woord.';tool.innerHTML=wall()}else{intro.textContent='Kies QR-kaartjes voor de kinderen of één klasposter.';tool.innerHTML=setup();document.querySelector('#makeQr').onclick=()=>qrCards(Math.max(1,Math.min(40,+document.querySelector('#qrCount').value||1)));document.querySelector('#makePoster').onclick=poster}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelector('#printButton').onclick=()=>{if(document.body.dataset.view==='homework'){document.querySelector('#hwPrint')?.click();return}document.body.dataset.view==='cards'&&document.querySelector('#cards .card.chosen')?printCardSelection():print()};show('cards');
