const app=document.querySelector('#app');
const room={left:90,top:120,width:360,height:600};
// Middelpunten berekend uit de echte JSON-posities en afmetingen.
const desks=[[139.2,214.5],[192.3,214.7],[262.1,215.2],[315.0,215.2],[386.7,215.2],[143.9,317.1],[227.1,317.1],[312.6,317.7],[398.2,318.9],[143.0,413.7],[227.0,414.5],[314.0,411.7],[401.1,410.8],[144.8,500.4],[228.2,502.4],[313.8,499.5],[404.8,500.0],[166.9,585.6],[221.3,586.2],[275.6,585.9],[329.1,586.0],[408.1,584.7]];
const fixed=[
 {id:'board-back',kind:'board',x:261.2,y:127.7,w:270.7,h:9,label:''},
 {id:'board-front',kind:'board',x:268.1,y:712.0,w:270.7,h:9,label:''},
 {id:'teacher',kind:'teacher',x:412.3,y:664.5,w:41.8,h:65.3,label:''},
 {id:'teacher-chair',kind:'chair',x:441,y:664.5,w:10,h:18,label:''},
 {id:'cabinet-back-left',kind:'cabinet',x:146.5,y:150.5,w:55,h:26.8,label:''},
 {id:'cabinet-back-1',kind:'cabinet',x:202.5,y:144.2,w:47.9,h:17.9,label:''},
 {id:'cabinet-back-2',kind:'cabinet',x:255.7,y:144.9,w:47.9,h:17.9,label:''},
 {id:'cabinet-back-3',kind:'cabinet',x:308.8,y:145.5,w:47.9,h:17.9,label:''},
 {id:'cabinet-back-right',kind:'cabinet',x:429.6,y:163.0,w:26.8,h:72.4,label:''},
 {id:'cabinet-front-left',kind:'cabinet',x:164.7,y:688.5,w:60.2,h:26.8,label:''},
 {id:'cabinet-left-back',kind:'cabinet wall-cabinet',x:105,y:225.9,w:12.2,h:210.1,label:''},
 {id:'cabinet-left-front',kind:'cabinet wall-cabinet',x:107,y:461.3,w:12.2,h:210.1,label:''},
 {id:'sink',kind:'sink',x:107.3,y:680.2,w:30.2,h:36,label:'🚰'},
 {id:'bin-place',kind:'placement-spot',x:207,y:681,w:22,h:30,label:''},
 {id:'door',kind:'door',x:117,y:625.2,w:54.1,h:54.1,label:''},
 {id:'window-left-back',kind:'window',x:90,y:222,w:10,h:180,label:''},
 {id:'window-left-front',kind:'window',x:90,y:462,w:10,h:180,label:''},
 {id:'window-right-back',kind:'window',x:450,y:210,w:10,h:150,label:''},
 {id:'window-right-middle',kind:'window',x:450,y:412,w:10,h:150,label:''},
 {id:'window-right-front',kind:'window',x:450,y:623,w:10,h:150,label:''}
];
const nameRounds=[
 {anchors:[['Noor',10]],tasks:[['Liv','L','desk-9','zit links van Noor'],['Adam','A','desk-11','zit rechts van Noor'],['Mila','M','desk-6','zit achter Noor']]},
 {anchors:[['Sam',15]],tasks:[['Elias','E','desk-14','zit links van Sam'],['Lina','L','desk-16','zit rechts van Sam'],['Nore','N','desk-11','zit achter Sam']]},
 {anchors:[['Emma',5],['Jules',7]],tasks:[['Mats','M','desk-6','zit tussen Emma en Jules'],['Fien','F','desk-9','zit voor Emma'],['Rayan','R','desk-1','zit achter Mats']]},
 {anchors:[['Mauro',2]],tasks:[['Lotte','L','desk-1','zit links van Mauro'],['Yana','Y','desk-3','zit rechts van Mauro'],['Finn','F','desk-6','zit schuin links voor Mauro']]},
 {anchors:[['Imani',18],['Seppe',20]],tasks:[['Aya','A','desk-19','zit tussen Imani en Seppe'],['Leon','L','desk-14','zit achter Imani'],['Lou','L','desk-15','zit achter Seppe']]},
 {anchors:[['Amir',11]],tasks:[['Zoë','Z','desk-10','zit links van Amir'],['Tuur','T','desk-12','zit rechts van Amir'],['Lio','L','desk-15','zit voor Amir']]},
 {anchors:[['Nina',11]],tasks:[['Omar','O','desk-6','zit schuin links achter Nina'],['Roos','R','desk-8','zit schuin rechts achter Nina'],['Vik','V','desk-15','zit voor Nina']]},
 {anchors:[['Bo',10]],tasks:[['Mira','M','desk-13','zit schuin links voor Bo'],['Ilias','I','desk-15','zit schuin rechts voor Bo'],['Kaat','K','desk-6','zit achter Bo']]},
 {anchors:[],tasks:[['Fleur','F','desk-20','zit op de eerste rij vooraan, op de vierde bank van links'],['Mathis','M','desk-7','zit op de voorlaatste rij, op de tweede bank vanaf rechts'],['Lena','L','desk-17','zit op de eerste rij vooraan, op de eerste bank van links']]},
 {anchors:[],tasks:[['Sami','S','desk-3','zit op de eerste rij achteraan, op de tweede bank vanaf rechts'],['Ella','E','desk-7','zit op de tweede rij achteraan, op de derde bank van links'],['Raf','R','desk-12','zit op de derde rij achteraan, op de eerste bank vanaf rechts']]}
];
const objectRounds=[
 {tasks:[['de computer','💻','teacher','staat op het bureau van de juf'],['de plant','🪴','cabinet-back-right','staat op de kast rechts achteraan'],['het boek','📘','desk-6','ligt op de tweede bank van links in de tweede rij vanaf achteraan']]},
 {tasks:[['de boekentas','🎒','desk-14','staat bij de tweede bank van links in de vierde rij vanaf achteraan'],['de spons','🧽','board-front','ligt bij het bord vooraan'],['de drinkfles','🧴','sink','staat bij de wastafel']]},
 {tasks:[['de klok','🕐','board-back','hangt bij het bord achteraan'],['de doos','📦','cabinet-front-left','staat op de kast links vooraan'],['de bal','⚽','desk-12','ligt bij de bank helemaal rechts in de derde rij vanaf achteraan']]},
 {tasks:[['de vuilbak','🗑️','bin-place','staat rechts naast het kastje links vooraan'],['de boekentas','🎒','desk-17','staat bij de bank links vooraan'],['de plant','🪴','cabinet-back-left','staat op de kast links achteraan']]},
 {tasks:[['de schaar','✂️','desk-3','ligt op de tweede bank van rechts achteraan'],['de boeken','📚','cabinet-back-2','liggen in het midden op de kasten achteraan'],['de tablet','📱','teacher','ligt op het bureau van de juf']]},
 {tasks:[['de jas','🧥','door','hangt bij de deuropening'],['de brooddoos','🍱','desk-19','ligt op de middelste bank vooraan'],['de wereldbol','🌍','cabinet-back-3','staat op de kast rechts van het midden achteraan']]}
];
const mixedRounds=[
 {anchors:[['Noor',10]],tasks:[['Liv','L','desk-9','zit links van Noor'],['het boek','📘','desk-11','ligt op de bank rechts van Noor'],['de vuilbak','🗑️','bin-place','staat rechts naast het kastje links vooraan'],['de computer','💻','teacher','staat op het bureau van de juf']]},
 {anchors:[['Sam',15]],tasks:[['Elias','E','desk-14','zit links van Sam'],['Lina','L','desk-16','zit rechts van Sam'],['de boekentas','🎒','desk-20','staat bij de bank schuin rechts voor Sam'],['de plant','🪴','cabinet-back-right','staat op de kast rechts achteraan']]},
 {anchors:[['Emma',5],['Jules',7]],tasks:[['Mats','M','desk-6','zit tussen Emma en Jules'],['de drinkfles','🧴','sink','staat bij de wastafel'],['de doos','📦','cabinet-front-left','staat op de kast links vooraan'],['de klok','🕐','board-back','hangt bij het bord achteraan']]},
 {anchors:[['Mauro',2]],tasks:[['Yana','Y','desk-3','zit rechts van Mauro'],['Finn','F','desk-6','zit voor Mauro'],['de bal','⚽','desk-8','ligt op de bank helemaal rechts in de tweede rij'],['de spons','🧽','board-front','ligt bij het bord vooraan']]},
 {anchors:[['Imani',18],['Seppe',20]],tasks:[['Aya','A','desk-19','zit tussen Imani en Seppe'],['de brooddoos','🍱','desk-17','ligt op de bank helemaal links vooraan'],['de wereldbol','🌍','cabinet-back-3','staat op de kast rechts van het midden achteraan'],['de vuilbak','🗑️','bin-place','staat rechts naast het kastje links vooraan']]},
 {anchors:[['Amir',11]],tasks:[['Zoë','Z','desk-10','zit links van Amir'],['Lio','L','desk-15','zit voor Amir'],['de boeken','📚','cabinet-back-2','liggen op de kasten achteraan'],['de tablet','📱','teacher','ligt op het bureau van de juf']]}
];
const quiz=[
 ['Welk bord is vooraan in onze klas?','board-front',['board-front','board-back','door']],
 ['Waar staat het bureau van de juf?','teacher',['teacher','sink','cabinet-back-right']],
 ['Wat vind je links vooraan?','sink',['sink','cabinet-back-right','board-back']],
 ['Welke kast staat rechts achteraan?','cabinet-back-right',['cabinet-back-right','cabinet-front-left','teacher']],
 ['Tik de deur aan.','door',['door','window-left-front','window-right-front']],
 ['Welk raam ligt rechts in het midden?','window-right-middle',['window-right-middle','window-right-front','window-right-back']],
 ['Welk raam ligt rechts vooraan?','window-right-front',['window-right-front','window-left-front','window-right-back']],
 ['Wat vind je links van het bureau van de juf?','board-front',['board-front','cabinet-back-right','window-right-back']],
 ['Welke kast staat links vooraan?','cabinet-front-left',['cabinet-front-left','cabinet-back-right','teacher']],
 ['Waar vind je de wastafel?','sink',['sink','board-back','window-right-middle']],
 ['Tik de tweede bank van links aan op de eerste rij.','desk-18',['desk-18','desk-17','desk-19']],
 ['Tik de vierde bank van links aan op de voorlaatste rij.','desk-8',['desk-8','desk-7','desk-6']],
 ['Tik de derde bank van links aan op de tweede rij.','desk-15',['desk-15','desk-14','desk-16']],
 ['Tik de eerste bank van links aan op de derde rij.','desk-9',['desk-9','desk-10','desk-11']],
 ['Tik de tweede bank van links aan op de laatste rij.','desk-1',['desk-1','desk-0','desk-2']],
 ['Tik de vijfde bank van links aan op de eerste rij.','desk-21',['desk-21','desk-20','desk-17']]
];
const colorRounds=[
 {label:'banken',singular:'bank',kind:'desk',color:'oranje',spoken:'Geef alle banken de oranje kleur.'},
 {label:'bureaus van de juf',singular:'bureau van de juf',kind:'teacher',color:'groen',spoken:'Geef het bureau van de juf de groene kleur.'},
 {label:'borden',singular:'bord',kind:'board',color:'donkergroen',spoken:'Geef de twee borden de donkergroene kleur.'},
 {label:'kasten',singular:'kast',kind:'cabinet',color:'blauw',spoken:'Geef alle kasten de blauwe kleur.'},
 {label:'ramen',singular:'raam',kind:'window',color:'lichtblauw',spoken:'Geef alle ramen de lichtblauwe kleur.'},
 {label:'wastafels',singular:'wastafel',kind:'sink',color:'blauw',spoken:'Geef de wastafel de blauwe kleur.'}
];
let state={mode:null,round:0,index:0,mistakes:[],reviewErrors:[],review:false,items:[],placed:0,spoken:''};
const pctX=x=>(x-room.left)/room.width*100,pctY=y=>(y-room.top)/room.height*100;
function say(text=state.spoken){if(!text||!('speechSynthesis'in window))return;const s=speechSynthesis;s.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-BE';u.rate=.86;s.speak(u)}
function bindLeftRightHelp(){const button=document.querySelector('#help-lr'),map=document.querySelector('#room'),wrap=map?.closest('.room-wrap');if(!button||!map)return;button.onclick=()=>{const on=map.classList.toggle('lr-help');wrap?.classList.toggle('show-lr-help',on);button.textContent=on?'✓ Hulpje staat aan':'💡 Hulpje: links en rechts';button.setAttribute('aria-pressed',String(on))}}
function leftRightHelpHTML(text){return /\b(link(?:s|erkant)?|recht(?:s|erkant)?)\b/i.test(String(text).replace(/<[^>]*>/g,' '))?'<button class="secondary help-button" id="help-lr" aria-pressed="false">💡 Hulpje: links en rechts</button>':''}
document.querySelector('#sound').onclick=()=>say();
function menu(){state={mode:null,round:0,index:0,mistakes:[],reviewErrors:[],review:false,items:[],placed:0,spoken:'Kies een oefening over de plattegrond van onze klas of school.'};app.innerHTML=`<section class="welcome"><p>2de leerjaar · extra herhaling</p><h1>Plattegrond van klas en school</h1><p>Oefen met plaatsen, voorwerpen en mensen in onze klas en school.</p><div class="mode-grid"><button class="mode" data-mode="names"><i>🧒</i><h2>Zet de kinderen juist</h2><p>Links, rechts, voor, achter en tussen.</p></button><button class="mode" data-mode="objects"><i>🪴</i><h2>Plaats de voorwerpen</h2><p>Op een bank, kast, bord of bureau.</p></button><button class="mode" data-mode="mixed"><i>🧒🪴</i><h2>Alles door elkaar</h2><p>Plaats kinderen én voorwerpen in dezelfde ronde.</p></button><button class="mode" data-mode="quiz"><i>🧭</i><h2>Waar is het?</h2><p>Herken vooraan, achteraan, links en rechts.</p></button><button class="mode" data-mode="colors"><i>🎨</i><h2>Kleur onze klas</h2><p>Tik alle banken, kasten, borden en andere delen aan.</p></button></div></section>`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));say()}
function start(mode){state.mode=mode;state.round=0;state.index=0;state.mistakes=[];state.reviewErrors=[];state.review=false;state.items=mode==='quiz'?[...quiz]:mode==='names'?[...nameRounds]:mode==='mixed'?[...mixedRounds]:mode==='colors'?[...colorRounds]:[...objectRounds];for(let i=state.items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[state.items[i],state.items[j]]=[state.items[j],state.items[i]]}render()}
function roomHTML(anchors=[],extraClass=''){return `<div class="orientation" style="justify-content:center"><span>⬆ ACHTERAAN</span></div><div class="room ${extraClass}" id="room">${desks.map((d,i)=>`<button class="furniture desk" id="desk-${i}" data-target="desk-${i}" data-kind="desk" style="left:${pctX(d[0])}%;top:${pctY(d[1])}%;width:15%;height:5%;transform:translate(-50%,-50%)" aria-label="bank ${i+1}"></button>`).join('')}${fixed.map(o=>`<button class="furniture ${o.kind}" id="${o.id}" data-target="${o.id}" data-kind="${o.kind.split(' ')[0]}" style="left:${pctX(o.x)}%;top:${pctY(o.y)}%;width:${o.w/room.width*100}%;height:${Math.max(o.h/room.height*100,2.4)}%;transform:translate(-50%,-50%)">${o.label}</button>`).join('')}${anchors.map(a=>tokenHTML(a[0],desks[a[1]],'anchor')).join('')}</div><div class="lr-guide" aria-hidden="true"><span>← LINKS</span><span>RECHTS →</span></div><div class="orientation front" style="justify-content:center;padding-top:8px"><span>VOORAAN ⬇</span></div>`}
function tokenHTML(label,pos,cls='placed-token'){return `<span class="${cls}" style="left:${pctX(pos[0])}%;top:${pctY(pos[1])}%">${label}</span>`}
function render(){if(state.index>=state.items.length)return finish();if(state.mode==='names')renderPlacement(state.items[state.index],'names');if(state.mode==='objects')renderPlacement(state.items[state.index],'objects');if(state.mode==='mixed')renderPlacement(state.items[state.index],'mixed');if(state.mode==='quiz')renderQuiz(state.items[state.index]);if(state.mode==='colors')renderColor(state.items[state.index])}
function renderPlacement(roundData,type){state.placed=0;const tasks=roundData.tasks;const anchors=roundData.anchors||[];const mixed=type==='mixed';state.spoken=type==='names'?`Sleep de ${tasks.length} kinderen naar de juiste bank. Luister goed naar links, rechts, schuin links, schuin rechts, voor, achter en tussen.`:mixed?`Sleep de kinderen en voorwerpen naar de juiste plaats in de klas.`:`Sleep de ${tasks.length} voorwerpen naar de juiste plaats in de klas.`;const title=type==='names'?'Zet de kinderen juist':mixed?'Plaats alles juist':'Plaats de voorwerpen',helpText=tasks.map(t=>t[3]).join(' ');app.innerHTML=`<div class="game-head"><h1>${title}</h1><span class="counter">${state.index+1} / ${state.items.length}</span></div><div class="game-layout"><section class="room-wrap">${roomHTML(anchors)}</section><aside class="side"><p class="instruction">${state.spoken}</p><div class="tasks">${tasks.map((t,i)=>`<div class="task" data-task="${i}"><button class="drag-token" data-i="${i}" data-target="${t[2]}" aria-label="Sleep ${t[0]}">${t[1]}</button><span><strong>${t[0]}</strong>${t[3]}</span></div>`).join('')}</div><p class="feedback" id="feedback"></p><div class="actions"><button class="secondary" id="listen">🔊 Luister</button>${leftRightHelpHTML(helpText)}</div></aside></div>`;document.querySelector('#listen').onclick=()=>say();bindLeftRightHelp();bindTokens(tasks)}
function bindTokens(tasks){document.querySelectorAll('.drag-token').forEach(token=>{let ghost=null,moved=false;const expectedNear=(x,y)=>{const wanted=document.querySelector(`[data-target="${token.dataset.target}"]`);if(!wanted)return null;const r=wanted.getBoundingClientRect(),margin=Math.max(16,Math.min(28,r.width*.22));return x>=r.left-margin&&x<=r.right+margin&&y>=r.top-margin&&y<=r.bottom+margin?wanted:null};const drop=(target)=>{if(!target)return;const right=target.dataset.target===token.dataset.target;if(!right){remember();feedback('Nog niet. Kijk en luister opnieuw.','bad');target.classList.add('wrong');setTimeout(()=>target.classList.remove('wrong'),450);return}const i=Number(token.dataset.i),task=tasks[i],pos=target.id.startsWith('desk-')?desks[Number(target.id.slice(5))]:[fixed.find(o=>o.id===target.id).x,fixed.find(o=>o.id===target.id).y];document.querySelector('#room').insertAdjacentHTML('beforeend',tokenHTML(task[1],pos));token.closest('.task').classList.add('done');token.disabled=true;state.placed++;feedback('Goed geplaatst!','good');if(state.placed===tasks.length)setTimeout(next,700)};token.onclick=()=>{document.querySelectorAll('[data-target]').forEach(t=>{t.onclick=()=>drop(t)})};token.onpointerdown=e=>{if(token.disabled)return;e.preventDefault();moved=false;token.setPointerCapture(e.pointerId);ghost=document.createElement('span');ghost.className='ghost';ghost.textContent=token.textContent;document.body.append(ghost);ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px'};token.onpointermove=e=>{if(!ghost)return;moved=true;ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';document.querySelectorAll('.drop-target').forEach(t=>t.classList.remove('drop-target'));const target=expectedNear(e.clientX,e.clientY)||document.elementsFromPoint(e.clientX,e.clientY).map(x=>x.closest?.('[data-target]')).find(Boolean);target?.classList.add('drop-target')};token.onpointerup=e=>{if(!ghost)return;const target=expectedNear(e.clientX,e.clientY)||document.elementsFromPoint(e.clientX,e.clientY).map(x=>x.closest?.('[data-target]')).find(Boolean);ghost.remove();ghost=null;document.querySelectorAll('.drop-target').forEach(t=>t.classList.remove('drop-target'));if(moved)drop(target)};token.onpointercancel=()=>{ghost?.remove();ghost=null}})}
function renderQuiz(q){state.spoken=`${q[0]} Tik het juiste onderdeel aan in de plattegrond.`;app.innerHTML=`<div class="game-head"><h1>Waar is het?</h1><span class="counter">${state.index+1} / ${state.items.length}</span></div><div class="game-layout"><section class="room-wrap">${roomHTML([],'quiz-room')}</section><aside class="side"><p class="instruction">${q[0]}</p><p class="small-help">Tik het juiste onderdeel aan in de plattegrond.</p><p class="feedback" id="feedback"></p><div class="actions"><button class="secondary" id="listen">🔊 Luister</button>${leftRightHelpHTML(q[0])}</div></aside></div>`;document.querySelector('#listen').onclick=()=>say();bindLeftRightHelp();let answered=false;document.querySelectorAll('#room [data-target]').forEach(el=>el.onclick=()=>{if(answered)return;const right=el.dataset.target===q[1];if(!right){remember();el.classList.add('wrong');feedback('Dat is het niet. Kijk nog eens goed.','bad');setTimeout(()=>el.classList.remove('wrong'),500);return}answered=true;el.classList.add('drop-target');feedback('Juist gevonden!','good');setTimeout(next,650)})}
function renderColor(roundData){state.spoken=`${roundData.spoken} Klik daarna op: Ik ben klaar.`;app.innerHTML=`<div class="game-head"><h1>Kleur onze klas</h1><span class="counter">${state.index+1} / ${state.items.length}</span></div><div class="game-layout"><section class="room-wrap">${roomHTML([],'color-room')}</section><aside class="side"><p class="instruction">${roundData.spoken}</p><div class="paint-swatch paint-${roundData.kind}">${roundData.color}</div><p class="small-help">Tik alle juiste delen aan. Klik daarna op <strong>Ik ben klaar</strong>.</p><p class="color-count" id="color-count">0 gevonden</p><p class="feedback" id="feedback"></p><div class="actions"><button class="primary" id="check-color">Ik ben klaar</button><button class="secondary" id="listen">🔊 Luister</button></div></aside></div>`;document.querySelector('#listen').onclick=()=>say();const targets=[...document.querySelectorAll(`[data-kind="${roundData.kind}"]`)];let found=0;const updateCount=()=>{document.querySelector('#color-count').textContent=`${found} gevonden`};document.querySelectorAll('#room [data-kind]').forEach(el=>el.onclick=()=>{if(el.classList.contains('painted'))return;if(el.dataset.kind!==roundData.kind){remember();el.classList.add('wrong');feedback('Dat hoort niet bij deze opdracht. Probeer opnieuw.','bad');setTimeout(()=>el.classList.remove('wrong'),450);return}el.classList.add('painted',`paint-${roundData.kind}`);found++;updateCount();feedback('Goed! Kijk of je ze allemaal hebt.','good')});document.querySelector('#check-color').onclick=()=>{const missing=targets.length-found;if(missing>0){remember();feedback(`Je mist nog ${missing} ${missing===1?roundData.singular:roundData.label}. Kijk nog eens goed.`,'bad');return}feedback('Alles juist gekleurd!','good');setTimeout(next,650)}}
function labelFor(id){return ({'board-front':'het bord vooraan','board-back':'het bord achteraan',teacher:'het bureau van de juf',sink:'de wastafel',door:'de deur','bin-place':'rechts naast het kastje links vooraan','cabinet-back-right':'de kast rechts achteraan','cabinet-front-left':'de kast links vooraan','window-left-front':'het raam links vooraan','window-right-front':'het raam rechts vooraan','window-right-back':'het raam rechts achteraan','window-right-middle':'het raam rechts in het midden'})[id]||id}
function remember(){const item=state.items[state.index],list=state.review?state.reviewErrors:state.mistakes;if(!list.includes(item))list.push(item)}
function feedback(text,kind){const el=document.querySelector('#feedback');el.textContent=text;el.className=`feedback ${kind}`;say(text)}
function next(){state.index++;render()}
function finish(){const errors=state.review?state.reviewErrors:state.mistakes;if(errors.length){state.review=true;state.items=[...errors];state.reviewErrors=[];state.index=0;state.spoken='Nu komen de opdrachten die nog moeilijk waren opnieuw.';app.innerHTML=`<section class="result"><div class="emoji">💪</div><h1>Foutenronde</h1><p>De moeilijke opdrachten komen opnieuw tot ze juist zijn.</p><button class="primary" id="review">Oefen mijn foutjes</button></section>`;document.querySelector('#review').onclick=render;say();return}state.spoken='Klaar. Je hebt de plattegrond goed geoefend.';app.innerHTML=`<section class="result"><div class="emoji">🏆</div><h1>Klaar!</h1><p>Je kent onze klas al veel beter.</p><button class="primary" id="again">Kies een andere oefening</button></section>`;document.querySelector('#again').onclick=menu;say()}
const qrDialog=document.querySelector('#qrDialog');document.querySelector('#qrButton').onclick=()=>{qrDialog.showModal();const box=document.querySelector('#qrBox');box.replaceChildren();if(window.QRCode&&location.protocol!=='file:'){new QRCode(box,{text:location.href,width:220,height:220,colorDark:'#176b62',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});document.querySelector('#qrMessage').textContent=location.href}else{box.textContent=location.protocol==='file:'?'De QR-code verschijnt zodra deze pagina online staat.':'De QR-code kon niet worden geladen.';document.querySelector('#qrMessage').textContent=''}};document.querySelector('#closeQr').onclick=()=>qrDialog.close();document.querySelector('#printQr').onclick=()=>window.print();
const originalMenu=menu,originalStart=start;
menu=function(){document.querySelector('#allThemes').hidden=false;document.querySelector('#exerciseMenuButton').hidden=true;return originalMenu()};
start=function(mode){document.querySelector('#allThemes').hidden=true;document.querySelector('#exerciseMenuButton').hidden=false;return originalStart(mode)};
document.querySelector('#exerciseMenuButton').onclick=()=>menu();
menu();
