const app=document.querySelector('#app');let state={mode:null,i:0,list:[],mistakes:[],review:false,spoken:''};
const img={forest:'assets/images/boslagen-realistisch.png',mushroom:'assets/images/paddenstoelen-realistisch.png',squirrel:'assets/images/eekhoorn-realistisch.png',spider:'assets/images/kruisspin-realistisch.png'};
const sets={
 rules:[['Waarom blijf je in het bos op het pad?','Dan stoor en beschadig je minder','Dan groeien bomen sneller','Dan vind je meer afval',0,'forest'],['Wat doe je met een lege verpakking?','Je laat ze bij een boom liggen','Je neemt ze mee','Je verstopt ze onder mos',1,'forest'],['Waarom maak je geen luid lawaai?','Om de dieren rust te geven','Omdat bomen kunnen schrikken','Om sneller te wandelen',0,'forest'],['Wat betekent respect voor het bos?','Alles meenemen wat mooi is','De regels volgen en de natuur heel laten','Zo luid mogelijk spelen',1,'forest']],
 layers:[['Waar groeien de hoogste bomen?','in de boomlaag','in de kruidlaag','in de moslaag',0,'forest'],['Waar vind je mos en paddenstoelen?','in de struiklaag','in de moslaag','in de boomlaag',1,'forest'],['Waar groeien varens, gras en bloemen?','in de kruidlaag','in de boomlaag','in de struiklaag',0,'forest'],['Welke laag krijgt het minste licht?','de boomlaag','de moslaag','de struiklaag',1,'forest'],['Waar vind je struiken en jonge bomen?','in de moslaag','in de kruidlaag','in de struiklaag',2,'forest']],
 mushroom:[['Welk deel zit bovenaan de paddenstoel?','de steel','de hoed','de zwamvlok',1,'mushroom'],['Wat zie je onder de hoed van de linker paddenstoel?','plaatjes','bladeren','wortels',0,'mushroom'],['Wat zie je onder de hoed van de rechter paddenstoel?','een vacht','buisjes','takken',1,'mushroom'],['Welk deel zit meestal onder de grond?','de ring','de hoed','de zwamvlok',2,'mushroom'],['Hoe planten paddenstoelen zich voort?','met sporen','met noten','met veren',0,'mushroom']],
 squirrel:[['Waarom is de eekhoorn een zoogdier?','Hij komt uit een ei','Hij krijgt als jong melk van zijn moeder','Hij heeft acht poten',1,'squirrel'],['Wat helpt de eekhoorn bij sturen en landen?','zijn pluimstaart','zijn oren','zijn nest',0,'squirrel'],['Waar maakt de eekhoorn zijn nest?','hoog in een boom','onder water','in een web',0,'squirrel'],['Wat eet een eekhoorn?','alleen gras','noten, zaden, bessen en soms insecten','alleen vlees',1,'squirrel'],['Welke dieren kunnen een eekhoorn opeten?','een vos en een roofvogel','een mier en een vlieg','een konijn en een ree',0,'squirrel']],
 spider:[['Hoeveel poten heeft een spinachtige?','zes','acht','tien',1,'spider'],['Hoeveel poten heeft een insect?','zes','acht','vier',0,'spider'],['Uit welke twee grote delen bestaat een spin?','kopborststuk en achterlijf','hoed en steel','kop en vacht',0,'spider'],['Waarmee vangt de kruisspin haar prooi?','met haar web','met haar nest','met haar vacht',0,'spider'],['Waarom zijn spinnen nuttig?','Ze eten veel insecten','Ze maken bladeren','Ze planten bomen',0,'spider']],
 mix:[['Fauna betekent ...','alle dieren samen','alle planten samen','alle regels samen',0,'forest'],['Flora betekent ...','alle dieren samen','alle planten, bloemen en bomen samen','alle paddenstoelen samen',1,'forest'],['Een paddenstoel is ...','een dier','een plant','een schimmel',2,'mushroom'],['Wat is een prooi?','een dier dat gevangen en opgegeten wordt','een jong van een zoogdier','een deel van een boom',0,'spider'],['Wat is een loofboom?','een boom met bladeren','een boom met alleen naalden','een jonge struik',0,'forest'],['Wat is een naaldboom?','een boom met bloemen','een boom met naalden','een boom zonder schors',1,'forest']]
};
const modes=[['rules','🌳','Bosregels','Wat mag wel en niet in het bos?'],['layers','🌿','De lagen van het bos','Boomlaag, struiklaag, kruidlaag en moslaag.'],['mushroom','🍄','De paddenstoel','Hoed, plaatjes, buisjes, steel, ring en zwamvlok.'],['squirrel','🐿️','De eekhoorn','Kenmerken, voedsel, nest en zoogdieren.'],['spider','🕷️','Insect of spinachtige','Zes of acht poten, bouw, web en prooi.'],['mix','🧠','Alles door elkaar','Woordenschat, voedselketen en toetsvragen.']];
function say(t=state.spoken){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='nl-BE';u.rate=.86;speechSynthesis.speak(u)}document.querySelector('#sound').onclick=()=>say();
function menu(){state={mode:null,i:0,list:[],mistakes:[],review:false,spoken:'Kies wat je wilt oefenen over het bos.'};app.innerHTML=`<section class="welcome"><p>2de leerjaar · thema 2</p><h1>Het bos, mijn vriend</h1><p>Kies een oefening. Je kunt elke opdracht laten voorlezen.</p><div class="teacher-tools"><a href="woordenschat.html">🖼️<b>Wandplaten en kaartjes</b><span>Bekijk of print de woordenschat.</span></a><a href="klassikaal.html">🎲<b>Klassikaal woordenschatspel</b><span>Luister, zoek, vertel en beeld uit.</span></a></div><div class="menu">${modes.map(m=>`<button class="mode" data-mode="${m[0]}"><i>${m[1]}</i><h2>${m[2]}</h2><p>${m[3]}</p></button>`).join('')}</div></section>`;document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>start(b.dataset.mode))}
function start(mode){state.mode=mode;state.i=0;state.list=[...sets[mode]];state.mistakes=[];state.review=false;render()}
function render(){if(state.i>=state.list.length)return finish();let q=state.list[state.i];state.spoken=q[0];app.innerHTML=`<div class="head"><h1>${modes.find(m=>m[0]===state.mode)[2]}</h1><span class="counter">${state.i+1} / ${state.list.length}${state.review?' · foutenronde':''}</span></div><section class="game"><img class="photo" src="${img[q[5]]}" alt="Realistische foto bij de vraag"><div class="panel"><div class="question-row"><button class="question-sound" aria-label="Lees de vraag voor">🔊</button><p class="question">${q[0]}</p></div><div class="answers">${q.slice(1,4).map((a,i)=>`<div class="answer-row"><button class="answer-sound" data-say="${a}" aria-label="Lees dit antwoord voor">🔊</button><button class="answer" data-i="${i}" data-color="${['rood','blauw','geel'][i]}">${a}</button></div>`).join('')}</div><p class="feedback" id="feedback"></p><div class="actions"><button class="listen">🔊 Lees de vraag</button><button class="back">← Andere oefening</button></div></div></section>`;document.querySelector('.question-sound').onclick=()=>say(q[0]);document.querySelector('.listen').onclick=()=>say(q[0]);document.querySelectorAll('.answer-sound').forEach(b=>b.onclick=()=>say(b.dataset.say));document.querySelector('.back').onclick=menu;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(b,q))}
function answer(b,q){let right=Number(b.dataset.i)===q[4],fb=document.querySelector('#feedback');if(!right){if(!state.mistakes.includes(q))state.mistakes.push(q);b.classList.add('bad');fb.textContent='Nog niet. Probeer opnieuw.';say(fb.textContent);setTimeout(()=>b.classList.remove('bad'),450);return}document.querySelectorAll('.answer').forEach(x=>x===b?x.classList.add('good'):x.classList.add('dim'));fb.textContent='Juist!';say('Juist!');setTimeout(()=>{state.i++;render()},700)}
function finish(){if(!state.review&&state.mistakes.length){state.review=true;state.list=[...state.mistakes];state.mistakes=[];state.i=0;return render()}app.innerHTML=`<section class="finish"><div style="font-size:70px">🌟</div><h1>Knap gewerkt!</h1><p>Je hebt deze oefening helemaal afgerond.</p><button id="again">Kies een andere oefening</button></section>`;document.querySelector('#again').onclick=menu;say('Knap gewerkt!')}
const qrDialog=document.querySelector('#qrDialog');document.querySelector('#qrButton').onclick=()=>{qrDialog.showModal();const box=document.querySelector('#qrBox');box.replaceChildren();if(window.QRCode&&location.protocol!=='file:'){new QRCode(box,{text:location.href,width:220,height:220,colorDark:'#315b2a',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});document.querySelector('#qrMessage').textContent=location.href}else{box.textContent=location.protocol==='file:'?'De QR-code verschijnt zodra deze pagina online staat.':'De QR-code kon niet worden geladen.';document.querySelector('#qrMessage').textContent=''}};document.querySelector('#closeQr').onclick=()=>qrDialog.close();document.querySelector('#printQr').onclick=()=>window.print();
menu();
