const app=document.querySelector('#app'),title=document.querySelector('#title');let spoken='Kies een sleepoefening.',selected=null;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);const say=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(spoken);u.lang='nl-BE';u.rate=.86;speechSynthesis.speak(u)};document.querySelector('#speak').onclick=say;
const configs={tree:{title:'Delen van de boom',instruction:'Sleep elk woord naar het juiste deel van de boom.',image:'assets/images/boom-delen-realistisch.png',items:[['de kruin',50,10],['de bladeren',76,25],['de takken',27,32],['de stam',67,58],['de wortels',50,84]]},mushroom:{title:'Delen van de paddenstoel',instruction:'Sleep elk woord naar het juiste deel van de paddenstoel.',image:'assets/images/paddenstoel-delen-realistisch.png',items:[['de hoed',58,7],['de plaatjes',24,26],['de sporen',77,31],['de ring',72,48],['de steel',23,57],['de zwamvlok',55,83]]}};
function menu(){title.textContent='Sleepoefeningen';spoken='Kies een oefening. Delen van de boom, delen van de paddenstoel, groei van de paddenstoel, of de kruisspin vangt een prooi.';app.innerHTML=`<p class="instruction">Wat wil je oefenen?</p><section class="chooser"><button data-kind="tree">🌳 Delen van de boom</button><button data-kind="mushroom">🍄 Delen van de paddenstoel</button><button data-kind="cycle">🔄 Groei van de paddenstoel</button><button data-kind="spider-cycle">🕸️ De kruisspin vangt een prooi</button></section>`;document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{if(b.dataset.kind==='cycle')cycle();else if(b.dataset.kind==='spider-cycle')spiderCycle();else labels(b.dataset.kind)})}
function wire(drags,drops,onDrop){drags.forEach(d=>{d.draggable=true;d.onclick=()=>{drags.forEach(x=>x.classList.remove('selected'));selected=d;d.classList.add('selected')};d.ondragstart=e=>e.dataTransfer.setData('text/plain',d.dataset.key)});drops.forEach(z=>{z.ondragover=e=>{e.preventDefault();z.classList.add('over')};z.ondragleave=()=>z.classList.remove('over');z.ondrop=e=>{e.preventDefault();z.classList.remove('over');onDrop(e.dataTransfer.getData('text/plain'),z)};z.onclick=()=>{if(selected)onDrop(selected.dataset.key,z)}})}
function labels(kind){const c=configs[kind];title.textContent=c.title;spoken=c.instruction;app.innerHTML=`<p class="instruction">${c.instruction}</p><section class="board"><div class="diagram"><img src="${c.image}" alt="${c.title}">${c.items.map(([w,x,y])=>`<div class="drop" data-key="${w}" style="left:${x}%;top:${y}%;transform:translate(-50%,-50%)"></div>`).join('')}</div><div><div class="bank">${shuffle(c.items).map(([w])=>`<button class="chip" data-key="${w}">${w}</button>`).join('')}</div><p class="feedback"></p></div></section>`;const drags=[...document.querySelectorAll('.chip')],drops=[...document.querySelectorAll('.drop')];wire(drags,drops,(key,z)=>{const d=drags.find(x=>x.dataset.key===key);if(!d)return;if(z.dataset.key!==key){document.querySelector('.feedback').textContent='Nog niet. Kijk opnieuw.';return}z.textContent=key;z.classList.add('good');d.remove();selected=null;document.querySelector('.feedback').textContent='Goed geplaatst!';if(!document.querySelector('.chip'))setTimeout(done,600)})}
const stages=[['sporen',0],['zwamvlok',1],['bolletje',2],['groeien',3],['paddenstoel',4]];
function cycle(){title.textContent='Groei van de paddenstoel';spoken='Zet de prenten en woorden in de juiste volgorde. Begin bij de sporen.';app.innerHTML=`<p class="instruction">Sleep de prenten in de juiste volgorde. Begin bij de sporen.</p><section class="cycle">${stages.map((_,i)=>`<div class="cycle-slot" data-order="${i}"></div>`).join('')}</section><div class="bank">${shuffle(stages).map(([w,i])=>`<div class="stage" data-key="${i}"><div class="crop" style="--i:${i}"></div><p>${w}</p></div>`).join('')}</div><div class="controls"><button class="primary" id="check">Ik ben klaar</button></div><p class="feedback"></p>`;const drags=[...document.querySelectorAll('.stage')],drops=[...document.querySelectorAll('.cycle-slot')];wire(drags,drops,(key,z)=>{const d=drags.find(x=>x.dataset.key===key);if(!d)return;z.replaceChildren(d);selected=null});document.querySelector('#check').onclick=()=>{const correct=drops.every(z=>z.firstElementChild&&z.firstElementChild.dataset.key===z.dataset.order);document.querySelector('.feedback').textContent=correct?'Alles staat in de juiste volgorde!':'Er staat nog iets verkeerd of er ontbreekt een prent.';if(correct)setTimeout(done,800)}}
const spiderSteps=['Er komt spindraad uit het achterlijf.','Daarmee maakt de spin een web.','Een insect blijft in het web kleven.','De spin spant draden om haar prooi en spuit gif in haar prooi.','De spin zuigt het insect leeg.'];
function spiderCycle(){title.textContent='De kruisspin vangt een prooi';spoken='Wat gebeurt eerst en wat komt daarna? Plaats de vijf zinnen in de juiste volgorde.';app.innerHTML=`<p class="instruction">Wat gebeurt eerst? Wat komt daarna? Plaats de zinnen van 1 tot en met 5.</p><section class="sequence">${spiderSteps.map((_,i)=>`<div class="sequence-row"><b>${i+1}</b><div class="sentence-slot" data-order="${i}"></div></div>`).join('')}</section><div class="bank sentence-bank">${shuffle(spiderSteps.map((text,i)=>[text,i])).map(([text,i])=>`<button class="sentence-card" data-key="${i}">${text}</button>`).join('')}</div><div class="controls"><button class="primary" id="check">Ik ben klaar</button></div><p class="feedback"></p>`;const drags=[...document.querySelectorAll('.sentence-card')],drops=[...document.querySelectorAll('.sentence-slot')],bank=document.querySelector('.sentence-bank');wire(drags,drops,(key,z)=>{const d=drags.find(x=>x.dataset.key===key);if(!d)return;if(z.firstElementChild&&z.firstElementChild!==d)bank.append(z.firstElementChild);z.replaceChildren(d);selected=null});document.querySelector('#check').onclick=()=>{const correct=drops.every(z=>z.firstElementChild&&z.firstElementChild.dataset.key===z.dataset.order);document.querySelector('.feedback').textContent=correct?'Alles staat in de juiste volgorde!':'Er staat nog iets verkeerd of er ontbreekt een zin.';if(correct)setTimeout(done,800)}}
function done(){app.innerHTML=`<section class="done"><div style="font-size:70px">🌟</div><h1>Knap gewerkt!</h1><button class="primary" id="again">Kies een andere oefening</button></section>`;document.querySelector('#again').onclick=menu;speechSynthesis.cancel();spoken='Knap gewerkt!';say()}
menu();
