const sheets=['woordenschat-bomen-lagen.png','woordenschat-paddenstoel.png','woordenschat-dieren.png','woordenschat-bosregels.png'];
const data=[['de loofboom',0,0],['de naaldboom',0,1],['de schors',0,2],['het bos',0,3],['de boomlaag',0,4],['de struiklaag',0,5],['de kruidlaag',0,6],['de moslaag',0,7],['de hoed',1,0],['de steel',1,1],['de ring',1,2],['de plaatjes',1,3],['de buisjes',1,4],['de zwamvlok',1,5],['de sporenafdruk',1,6],['de schimmel',1,7],['de spinachtige',2,0],['het insect',2,1],['het kopborststuk',2,2],['de prooi',2,3],['de vacht',2,4],['zogen',2,5],['levendbarend',2,6],['zich voortplanten',2,7],['de flora',3,0],['de fauna',3,1],['giftig',3,2],['het pictogram',3,3],['respect',3,5],['de regel',3,6],['het zoogdier',3,7]];
const THEME='Het bos, mijn vriend',HOME=new URL('./',location.href).href,tool=document.querySelector('#tool'),intro=document.querySelector('#intro');
function cardMarkup(){return `<section id="cards">${data.map(([word,sheet,index])=>{const col=index%4,row=Math.floor(index/4);return `<article class="card"><div class="photo"><img src="assets/images/${sheets[sheet]}" alt="${word}" style="--col:${col};--row:${row}"></div><h2>${word}</h2></article>`}).join('')}</section>`}
const ACTIONS=new Set(['zogen','zich voortplanten']);
const POINTING=new Set(['de schors','de boomlaag','de struiklaag','de kruidlaag','de moslaag','de hoed','de steel','de ring','de plaatjes','de buisjes','de zwamvlok','het kopborststuk','de vacht','het pictogram']);
const HELP={'het bos':'Een gebied waar heel veel bomen bij elkaar staan.','de boomlaag':'De bovenste boslaag met hoge bomen; deze krijgt het meeste licht.','de buisjes':'Buisjes onder de hoed waaruit sporen komen.','de fauna':'Alle dieren samen.','de flora':'Alle planten, bloemen en bomen samen.','giftig':'Er zit gif in; het is gevaarlijk voor het lichaam.','de hoed':'Het bovenste deel van een paddenstoel.','het insect':'Een klein dier met zes poten, zoals een mier of bij.','het kopborststuk':'Het dikste lichaamsdeel van een spin.','de kruidlaag':'Boslaag met varens, gras en bloemen.','levendbarend':'De jongen worden levend geboren en komen niet uit een ei.','de loofboom':'Een boom met bladeren, zoals een eik of berk.','de moslaag':'De onderste boslaag met mos en paddenstoelen; deze krijgt het minste licht.','de naaldboom':'Een boom met naalden, zoals een den of spar.','het pictogram':'Een kleine prent of symbool met een betekenis.','de plaatjes':'Plaatjes onder de hoed; tussen de plaatjes zitten sporen.','de prooi':'Een dier dat door een roofdier wordt gevangen en opgegeten.','de regel':'Een afspraak waaraan je je moet houden.','respect':'Zorgzaam omgaan met de natuur en je aan de bosregels houden.','de ring':'Een deel op de steel, als een rokje rond de paddenstoel.','de schimmel':'Geen plant of dier; een opruimer van de natuur.','de schors':'De buitenste laag van stam en takken.','de spinachtige':'Een dier uit de groep van de geleedpotigen met acht poten.','de sporenafdruk':'De aftekening die paddenstoelsporen achterlaten.','de steel':'Het deel boven de grond en onder de hoed.','de struiklaag':'Boslaag met struiken en jonge bomen.','de vacht':'De haren die de huid van een dier bedekken.','zich voortplanten':'Ervoor zorgen dat er nieuwe mensen, dieren, planten of paddenstoelen komen.','zogen':'Een moeder geeft melk aan haar jong.','het zoogdier':'Een dier waarvan het jong in de moeder groeit en melk krijgt.','de zwamvlok':'Het ondergrondse deel van een paddenstoel.'};
function question(word,i){if(ACTIONS.has(word))return `Beeld “${word}” uit en leg daarna in je eigen woorden uit wat het betekent.`;if(POINTING.has(word))return `Wijs “${word}” aan op de wandplaat en leg uit waaraan je het herkent.`;return i%2?`Gebruik “${word}” in een goede zin waaruit de betekenis duidelijk wordt.`:`Leg in je eigen woorden uit wat “${word}” betekent.`}
function stripsMarkup(){return `<section class="strips">${data.map(([word],i)=>`<article class="strip"><b>${word}</b><span>${question(word,i)}</span><small><strong>Houvast leerkracht:</strong> ${HELP[word]||''}</small></article>`).join('')}</section>`}
const WALL_TEXT=new Set(['de fauna','de flora','giftig','de regel','respect','de schimmel','zich voortplanten','levendbarend']);
function wallMarkup(){return `<p class="wall-note">Formaat: 6,2 × 7,8 cm. Het woord wordt niet afgedrukt.</p><section class="wall-grid">${data.map(([word,sheet,index])=>{if(WALL_TEXT.has(word))return `<article class="wall-card"><div class="wall-description">${HELP[word]}</div></article>`;const col=index%4,row=Math.floor(index/4);return `<article class="wall-card"><div class="wall-sprite photo"><img src="assets/images/${sheets[sheet]}" alt="" style="--col:${col};--row:${row}"></div></article>`}).join('')}</section>`}
function qrSetup(){return `<section class="qr-setup"><h2>QR-kaartjes voor de kinderen</h2><label>Aantal kinderen <input id="qrCount" type="number" min="1" max="40" value="24"></label><div><button id="makeQr">Maak kaartjes</button><button id="makePoster">Maak één klasposter</button></div><p>De QR-code opent alleen de oefeningen van dit thema.</p></section><section id="qrOutput"></section>`}
function addQr(box,size){new QRCode(box,{text:HOME,width:size,height:size,colorDark:'#315b2a',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}
function qrCards(count){document.body.dataset.print='qr-cards';const out=document.querySelector('#qrOutput');out.className='qr-grid';out.innerHTML=Array.from({length:count},(_,i)=>`<article class="qr-card"><h2>Ik oefen</h2><h3>${THEME}</h3><div class="qr-code" id="qr-${i}"></div><p>Scan en oefen mee!</p></article>`).join('');document.querySelectorAll('.qr-code').forEach(x=>addQr(x,105))}
function qrPoster(){document.body.dataset.print='qr-poster';const out=document.querySelector('#qrOutput');out.className='qr-poster-wrap';out.innerHTML=`<article class="qr-poster"><p>ZISA WO SPELEN</p><h1>Ik oefen</h1><h2>${THEME}</h2><div id="posterQr"></div><strong>Scan de QR-code en oefen mee!</strong></article>`;addQr(document.querySelector('#posterQr'),260)}
function show(view){document.body.dataset.view=view;delete document.body.dataset.print;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='cards'){intro.textContent='Realistische wandplaten en woordkaarten met het woord duidelijk erbij.';tool.innerHTML=cardMarkup()}else if(view==='strips'){intro.textContent='Knip de strookjes uit. Trek elke dag één woordenschatvraag voor een kort klasmoment.';tool.innerHTML=stripsMarkup()}else if(view==='wall'){intro.textContent='Kaartjes op maat voor de sprekende muur, zonder het woord.';tool.innerHTML=wallMarkup()}else{intro.textContent='Kies hoeveel kleine QR-kaartjes je wilt afdrukken of maak één grote poster voor de klas.';tool.innerHTML=qrSetup();document.querySelector('#makeQr').onclick=()=>qrCards(Math.max(1,Math.min(40,Number(document.querySelector('#qrCount').value)||1)));document.querySelector('#makePoster').onclick=qrPoster}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelector('#printButton').onclick=()=>print();show('cards');
