const sheets=['woordenschat-bomen-lagen.png','woordenschat-paddenstoel.png','woordenschat-dieren.png','woordenschat-bosregels.png'];
const data=[['de loofboom',0,0],['de naaldboom',0,1],['de schors',0,2],['het bos',0,3],['de boomlaag',0,4],['de struiklaag',0,5],['de kruidlaag',0,6],['de moslaag',0,7],['de hoed',1,0],['de steel',1,1],['de ring',1,2],['de plaatjes',1,3],['de buisjes',1,4],['de zwamvlok',1,5],['de sporenafdruk',1,6],['de schimmel',1,7],['de spinachtige',2,0],['het insect',2,1],['het kopborststuk',2,2],['de prooi',2,3],['de vacht',2,4],['zogen',2,5],['levendbarend',2,6],['zich voortplanten',2,7],['de flora',3,0],['de fauna',3,1],['giftig',3,2],['het pictogram',3,3],['respect',3,5],['de regel',3,6],['het zoogdier',3,7]];
const THEME='Het bos, mijn vriend',HOME=new URL('./',location.href).href,tool=document.querySelector('#tool'),intro=document.querySelector('#intro');
function cardMarkup(){return `<section id="cards">${data.map(([word,sheet,index])=>{const col=index%4,row=Math.floor(index/4);return `<article class="card"><div class="photo"><img src="assets/images/${sheets[sheet]}" alt="${word}" style="--col:${col};--row:${row}"></div><h2>${word}</h2></article>`}).join('')}</section>`}
function question(word,i){const prompts=[`Wat betekent “${word}”? Leg het uit in je eigen woorden.`,`Maak een goede zin met “${word}”.`,`Geef een voorbeeld dat past bij “${word}”.`,`Wat weet jij al over “${word}”?`];return prompts[i%prompts.length]}
function stripsMarkup(){return `<section class="strips">${data.map(([word],i)=>`<article class="strip"><b>${word}</b><span>${question(word,i)}</span></article>`).join('')}</section>`}
function qrSetup(){return `<section class="qr-setup"><h2>QR-kaartjes voor de kinderen</h2><label>Aantal kinderen <input id="qrCount" type="number" min="1" max="40" value="24"></label><div><button id="makeQr">Maak kaartjes</button><button id="makePoster">Maak één klasposter</button></div><p>De QR-code opent alleen de oefeningen van dit thema.</p></section><section id="qrOutput"></section>`}
function addQr(box,size){new QRCode(box,{text:HOME,width:size,height:size,colorDark:'#315b2a',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}
function qrCards(count){document.body.dataset.print='qr-cards';const out=document.querySelector('#qrOutput');out.className='qr-grid';out.innerHTML=Array.from({length:count},(_,i)=>`<article class="qr-card"><h2>Ik oefen</h2><h3>${THEME}</h3><div class="qr-code" id="qr-${i}"></div><p>Scan en oefen mee!</p></article>`).join('');document.querySelectorAll('.qr-code').forEach(x=>addQr(x,105))}
function qrPoster(){document.body.dataset.print='qr-poster';const out=document.querySelector('#qrOutput');out.className='qr-poster-wrap';out.innerHTML=`<article class="qr-poster"><p>ZISA WO SPELEN</p><h1>Ik oefen</h1><h2>${THEME}</h2><div id="posterQr"></div><strong>Scan de QR-code en oefen mee!</strong></article>`;addQr(document.querySelector('#posterQr'),260)}
function show(view){document.body.dataset.view=view;delete document.body.dataset.print;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='cards'){intro.textContent='Realistische wandplaten en woordkaarten met het woord duidelijk erbij.';tool.innerHTML=cardMarkup()}else if(view==='strips'){intro.textContent='Knip de strookjes uit. Trek elke dag één woordenschatvraag voor een kort klasmoment.';tool.innerHTML=stripsMarkup()}else{intro.textContent='Kies hoeveel kleine QR-kaartjes je wilt afdrukken of maak één grote poster voor de klas.';tool.innerHTML=qrSetup();document.querySelector('#makeQr').onclick=()=>qrCards(Math.max(1,Math.min(40,Number(document.querySelector('#qrCount').value)||1)));document.querySelector('#makePoster').onclick=qrPoster}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelector('#printButton').onclick=()=>print();show('cards');
