const base='assets/images/';const data=[['het adres','foto-adres.webp'],['het huisnummer','huisnummer-realistisch.png'],['de straatnaam','straatnaam-realistisch.png'],['de postcode','postcode-realistisch.png'],['het afval','foto-afval.webp'],['hergebruiken','foto-hergebruiken-v2.png'],['recycleren','foto-recycleren.webp'],['afval verbranden','foto-afval-verbranden.webp'],['afval voorkomen','foto-afval-voorkomen-v2.png'],['de akkerbouw','landbouw-akkerbouw-foto.webp'],['het bestuur','foto-gemeentebestuur.webp'],['de burgemeester','burgemeester-greet-de-bruyn.png'],['de buurgemeente','kaart-buurgemeente-bornem.svg'],['de cultuur','ter-dilft.jpg'],['de deelgemeente','kaart-deelgemeente-bornem.svg'],['de dienst','brandweer-bornem.jpg'],['de gemeente','kaart-bornem.png'],['het gemeentehuis','gemeentehuis-bornem.jpg'],['de gids','foto-gids.webp'],['de glastuinbouw','landbouw-glastuinbouw-foto.webp'],['de handel','winkelstraat-bornem.jpg'],['de industrie','gebied-industriegebied-foto-v2.webp'],['het industriegebied','gebied-industriegebied-foto-v2.webp'],['de landbouw','landbouw-veeteelt-foto.webp'],['het landbouwgebied','gebied-landbouwgebied-foto-v2.webp'],['het landelijk landschap','landschap-kasteel-bornem.webp'],['de legende','legende-kaart-uitgesneden.webp'],['de luchtfoto','luchtfoto-school.png'],['het natuurgebied','gebied-natuurgebied-foto-v2.webp'],['de recreatie','breeven.jpg'],['het recreatiegebied','breeven.jpg'],['het stedelijk landschap','landschap-stad-stedelijk-2.webp'],['het stratenplan','stratenplan-school.png'],['het toerisme','kasteel-bornem.jpg'],['de tuinbouw','landbouw-tuinbouw-foto.webp'],['de vakcoördinaat','kaart-bornem.png'],['de veeteelt','landbouw-veeteelt-foto.webp'],['het openbaar vervoer','station-bornem.jpg'],['het woongebied','gebied-woongebied-foto-v2.webp']];
data.find(([word])=>word==='het adres')[1]='postkaart-adres-school.svg';
data.find(([word])=>word==='het stratenplan')[1]='stratenplan-school-wandplaat.png';
data.find(([word])=>word==='de deelgemeente')[1]='kaart-bornem-plaatsen-echt.png';
data.find(([word])=>word==='de buurgemeente')[1]='kaart-bornem-buurgemeenten-echt.png';
data.find(([word])=>word==='de vakcoördinaat')[1]='kaart-vakcoordinaat-bornem.svg';
data.find(([word])=>word==='de landbouw')[1]='landbouw-overzicht.png';
data.find(([word])=>word==='het adres')[1]='envelop-adres-school.svg';
const THEME='Op stap in Bornem',HOME=new URL('./',location.href).href,tool=document.querySelector('#tool'),intro=document.querySelector('#intro');
data.find(item=>item[0]==='de legende')[1]='legende-duidelijk-v2.svg';
function cards(){const regular=data.map(([word,img])=>`<article class="card"><img class="photo" src="${base+img}" alt="${word}"><h2>${word}</h2></article>`).join('');const traffic=`<article class="card"><img class="photo" src="${base}verkeersborden-f43-bornem.svg" alt="Plaatsnaamborden van Bornem, Hingene, Mariekerke en Weert"><h2>het plaatsnaambord</h2></article>`;return `<section id="cards">${regular}${traffic}</section>`}
const ACTIONS=new Set(['hergebruiken','recycleren','afval verbranden','afval voorkomen']);
const POINTING=new Set(['het adres','het huisnummer','de straatnaam','de postcode','de legende','de luchtfoto','het stratenplan','de vakcoördinaat']);
const HELP={
'het adres':'De plaats waar iemand woont: straatnaam, huisnummer, postcode en gemeente.','het afval':'Alles wat we niet meer nodig hebben en daarom weggooien.','hergebruiken':'Iets opnieuw gebruiken. Voorbeeld: een glazen bokaal opnieuw gebruiken om potloden in te zetten.','recycleren':'Afval sorteren zodat er iets nieuws van gemaakt kan worden.','afval verbranden':'Restafval wordt in grote ovens verbrand; de warmte kan elektriciteit maken.','afval voorkomen':'Ervoor zorgen dat je geen afval maakt.','de akkerbouw':'Zaden groeien op een akker en worden met machines geoogst.','het bestuur':'Een groep mensen die beslist wat er in de gemeente gebeurt.','de burgemeester':'De baas van de gemeente, die mee zorgt dat alles goed en veilig verloopt.','de buurgemeente':'Een gemeente naast jouw gemeente.','de cultuur':'Alles wat door mensen is gemaakt.','de deelgemeente':'Een kleiner deel dat bij een gemeente hoort.','de dienst':'Iets wat iemand voor een ander doet.','de gemeente':'Een dorp of stad met een eigen bestuur.','het gemeentehuis':'Het gebouw waarin het bestuur van de gemeente werkt.','de gids':'Iemand die bezoekers de weg wijst of rondleidt.','de glastuinbouw':'Groenten, fruit of bloemen kweken in een serre.','de handel':'Een winkel of het kopen en verkopen van producten.','het huisnummer':'Het nummer op een gebouw.','de industrie':'Fabrieken en het werk dat daar gebeurt.','het industriegebied':'Een gebied waar bijvoorbeeld fabrieken staan.','de landbouw':'Het werk van boeren: dieren kweken of voedsel telen.','het landbouwgebied':'Een gebied waar bijvoorbeeld akkers en weiden liggen.','het landelijk landschap':'Een landschap met veel velden, weinig huizen en veel groen.','de legende':'De uitleg van kleuren en symbolen op een kaart.','de luchtfoto':'Een foto die vanuit de lucht is genomen.','het natuurgebied':'Een beschermd of natuurlijk gebied, bijvoorbeeld een bos.','de postcode':'De code van een gemeente en een onderdeel van het adres.','de recreatie':'Vrijetijdsbesteding, bijvoorbeeld sporten of spelen.','het recreatiegebied':'Een gebied waar je kunt spelen, sporten, zwemmen of ontspannen.','het stedelijk landschap':'Een landschap met veel gebouwen en weinig groen.','de straatnaam':'De naam van de straat en een onderdeel van het adres.','het stratenplan':'Een kaart van de straten in een stad, dorp of wijk.','het toerisme':'Alles wat te maken heeft met plaatsen bezoeken buiten de eigen omgeving.','de tuinbouw':'Groenten, fruit of bloemen kweken en meestal met de hand oogsten.','de vakcoördinaat':'Een combinatie van letter en cijfer om een exacte plaats op een kaart te vinden.','de veeteelt':'Dieren kweken voor melk, eieren, vlees of wol.','het openbaar vervoer':'Vervoer dat iedereen mag gebruiken, zoals trein en bus.','het woongebied':'Een gebied waar mensen huizen bouwen en wonen.'};
HELP['de deelgemeente']='Een officieel deel van een gemeente. De vier officiële deelgemeenten zijn Bornem, Hingene, Mariekerke en Weert.';
HELP['de buurgemeente']='Een gemeente naast Bornem. Op de kaart staan Temse, Hamme, Puurs-Sint-Amands, Willebroek, Niel en Schelle opvallend aangeduid.';
function question(word,i){if(word==='de buurgemeente')return 'Zoek op de kaart: Temse, Hamme, Puurs-Sint-Amands, Willebroek, Niel en Schelle.';if(word==='de deelgemeente')return 'Zoek de vier officiële deelgemeenten op de kaart: Bornem, Hingene, Mariekerke en Weert.';if(word==='hergebruiken')return 'Geef een gewoon voorbeeld van iets dat je opnieuw kunt gebruiken.';if(ACTIONS.has(word))return `Leg uit wat “${word}” betekent en geef een eenvoudig voorbeeld.`;if(POINTING.has(word))return `Wijs “${word}” aan op de wandplaat en leg uit wat het betekent.`;return i%2?`Gebruik “${word}” in een goede zin waaruit de betekenis duidelijk wordt.`:`Leg in je eigen woorden uit wat “${word}” betekent.`}
function strips(){return `<section class="strips">${data.map(([word],i)=>`<article class="strip"><b>${word}</b><span>${question(word,i)}</span><small><strong>Houvast leerkracht:</strong> ${HELP[word]||''}</small></article>`).join('')}</section>`}
const WALL_KIND={verb:new Set(['hergebruiken','recycleren','afval verbranden','afval voorkomen']),person:new Set(['de burgemeester','de gids']),quality:new Set(['het landelijk landschap','het stedelijk landschap']),place:new Set(['de buurgemeente','de deelgemeente','de gemeente','het gemeentehuis','het industriegebied','het landbouwgebied','het natuurgebied','het recreatiegebied','het woongebied'])};
function wallKind(word){return Object.entries(WALL_KIND).find(([,words])=>words.has(word))?.[0]||'what'}
function wall(){return `<p class="wall-note">Formaat: 6,2 × 7,8 cm. Rood = werkwoord · geel = persoon · groen = hoe · paars = waar · oranje = wanneer · bruin = wat. Het woord wordt niet afgedrukt.</p><section class="wall-grid">${data.map(([word,img])=>`<article class="wall-card" data-kind="${wallKind(word)}"><img src="${base+img}" alt=""><div class="wall-description">${HELP[word]}</div></article>`).join('')}</section>`}
function mapPoster(){const button='display:inline-block;border-radius:15px;background:#145c57;color:white;padding:14px 22px;text-decoration:none;font-size:20px;font-weight:900';return `<section style="max-width:1100px;margin:0 auto;display:grid;gap:22px;justify-items:center"><h2 style="margin:8px 0 0">Stratenplan rond onze school</h2><img src="${base}stratenplan-school-wandplaat.png" alt="Stratenplan rond onze school De Linde met legende" style="display:block;width:100%;height:auto;border:4px solid #66aaa3;border-radius:22px;background:white"><div style="text-align:center"><a href="assets/downloads/Stratenplan_rond_De_Linde_A4_liggend.pdf" target="_blank" rel="noopener" style="${button}">📄 Open de A4-PDF</a><p style="margin:10px 0;color:#476474;font-weight:700">A4 liggend · met herkenningspunten en een legende</p></div><hr style="width:100%;border:0;border-top:3px solid #9fc9c2;margin:18px 0"><h2 style="margin:0">Voor de methode: twee routekaarten met vakcoördinaten</h2><img src="${base}stratenplan-bornem-vakcoordinaten.png" alt="Gedetailleerd stratenplan rond De Linde met kolommen A tot D en rijen 1 tot 4" style="display:block;width:100%;height:auto;border:4px solid #66aaa3;border-radius:22px;background:white"><div style="text-align:center"><a href="assets/downloads/2_exemplaren_stratenplan_Bornem_vakcoordinaten_A4_liggend.pdf" target="_blank" rel="noopener" style="${button}">📄 Open 2 exemplaren op A4</a><p style="margin:10px 0;color:#476474;font-weight:700">Gedetailleerde straten · twee identieke pagina's · A4 liggend · 1 cm bladrand · rooster A-D en 1-4</p></div></section>`}
function enableCardPrintChooser(){const cards=[...document.querySelectorAll('#cards .card')];if(!cards.length)return;const bar=document.createElement('div');bar.className='card-print-tools';bar.innerHTML='<button class="choose-cards">☑ Kies wandplaten</button><span class="selection-actions" hidden><button class="choose-all">Alles kiezen</button> <button class="primary print-chosen">🖨️ Print gekozen</button> <button class="primary print-large">↔ Vergroot op liggend A4</button></span>';tool.prepend(bar);cards.forEach((card,i)=>{const label=document.createElement('label');label.className='card-choice';label.innerHTML=`<input type="checkbox" aria-label="Kies wandplaat ${i+1}"> kiezen`;card.prepend(label);label.querySelector('input').onchange=e=>card.classList.toggle('chosen',e.target.checked)});const actions=bar.querySelector('.selection-actions'),choose=bar.querySelector('.choose-cards');choose.onclick=()=>{const active=document.querySelector('#cards').classList.toggle('selecting');actions.hidden=!active;choose.textContent=active?'✕ Stop met kiezen':'☑ Kies wandplaten'};bar.querySelector('.choose-all').onclick=()=>cards.forEach(card=>{card.classList.add('chosen');card.querySelector('input').checked=true});bar.querySelector('.print-chosen').onclick=()=>printCardSelection(false);bar.querySelector('.print-large').onclick=()=>printCardSelection(true)}
function printCardSelection(large){if(!document.querySelector('#cards .card.chosen')){alert('Vink eerst minstens één wandplaat aan.');return}document.body.dataset.print=large?'card-landscape':'card-selection';if(large){const style=document.createElement('style');style.id='cardPageStyle';style.textContent='@page{size:A4 landscape;margin:10mm}';document.head.append(style)}setTimeout(()=>print(),50)}
addEventListener('afterprint',()=>{delete document.body.dataset.print;document.querySelector('#cardPageStyle')?.remove()});
function setup(){return `<section class="qr-setup"><h2>QR-kaartjes voor de kinderen</h2><label>Aantal kinderen <input id="qrCount" type="number" min="1" max="40" value="24"></label><div><button id="makeQr">Maak kaartjes</button><button id="makePoster">Maak één klasposter</button></div><p>De QR-code opent alleen de oefeningen van dit thema.</p></section><section id="qrOutput"></section>`}
function addQr(box,size){new QRCode(box,{text:HOME,width:size,height:size,colorDark:'#145c57',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}function qrCards(n){document.body.dataset.print='qr-cards';const o=document.querySelector('#qrOutput');o.className='qr-grid';o.innerHTML=Array.from({length:n},(_,i)=>`<article class="qr-card"><h2>Ik oefen</h2><h3>${THEME}</h3><div class="qr-code" id="qr-${i}"></div><p>Scan en oefen mee!</p></article>`).join('');document.querySelectorAll('.qr-code').forEach(x=>addQr(x,105))}function poster(){document.body.dataset.print='qr-poster';const o=document.querySelector('#qrOutput');o.className='qr-poster-wrap';o.innerHTML=`<article class="qr-poster"><p>ZISA WO SPELEN</p><h1>Ik oefen</h1><h2>${THEME}</h2><div id="posterQr"></div><strong>Scan de QR-code en oefen mee!</strong></article>`;addQr(document.querySelector('#posterQr'),260)}
function show(v){document.body.dataset.view=v;delete document.body.dataset.print;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='cards'){intro.textContent='Realistische wandplaten en woordkaarten met het woord duidelijk erbij.';tool.innerHTML=cards();enableCardPrintChooser()}else if(v==='strips'){intro.textContent='Knip de strookjes uit en trek elke dag één woordenschatvraag.';tool.innerHTML=strips()}else if(v==='map'){intro.textContent='Bekijk het stratenplan of open de printklare PDF op liggend A4.';tool.innerHTML=mapPoster()}else if(v==='wall'){intro.textContent='Kaartjes op maat voor de sprekende muur, zonder het woord.';tool.innerHTML=wall()}else{intro.textContent='Kies kleine QR-kaartjes voor de kinderen of één grote poster.';tool.innerHTML=setup();document.querySelector('#makeQr').onclick=()=>qrCards(Math.max(1,Math.min(40,Number(document.querySelector('#qrCount').value)||1)));document.querySelector('#makePoster').onclick=poster}}
const mapButton=document.createElement('button');mapButton.dataset.view='map';mapButton.textContent='🗺️ Stratenplan';document.querySelector('[data-view="qr"]').before(mapButton);
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelector('#printButton').onclick=()=>{if(document.body.dataset.view==='map'){location.href='assets/downloads/Stratenplan_rond_De_Linde_A4_liggend.pdf';return}if(document.body.dataset.view==='cards'&&document.querySelector('#cards .card.chosen')){printCardSelection(false);return}print()};show('cards');
