const objects=[['stoel','stoel'],['lessenaar','lessenaar'],['bureau-juf','bureau van de juf'],['bord','bord'],['boekenkast','boekenkast'],['kast','kast'],['vuilnisbak','vuilnisbak'],['penselen','penselen'],['plakband','plakband']];
const maps=[['schatkaart','schatkaart'],['plattegrond','plattegrond'],['maquette','maquette']];
const pictos=[['toilet','toilet'],['uitgang','uitgang'],['vuilnisbak','vuilnisbak']];
const app=document.querySelector('#app'),speakButton=document.querySelector('#speak'),allThemes=document.querySelector('#allThemes'),gameMenu=document.querySelector('#gameMenu');
let state={game:null,index:0,score:0,items:[],spoken:''};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const sample=(a,n)=>shuffle(a).slice(0,n);
function speak(text=state.spoken){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-BE';u.rate=.82;u.pitch=1.05;window.speechSynthesis.speak(u)}
speakButton.onclick=()=>speak();
function menu(){window.speechSynthesis?.cancel();state={game:null,index:0,score:0,items:[],spoken:'Kies een spelletje.'};allThemes.hidden=false;gameMenu.hidden=true;app.innerHTML=`<section class="welcome"><div><p class="eyebrow">THEMA 1 · 1STE LEERJAAR</p><h1>Verken je klas!</h1><p>Kijk, luister en tik op de juiste prent.</p></div><img src="assets/maquette.webp" alt="Een maquette van een klas"></section><h2 class="title">Kies een spelletje</h2><section class="games"><button class="game" data-game="objects"><span class="emoji">🎒</span><strong>In onze klas</strong><small>Vind het juiste voorwerp.</small></button><button class="game" data-game="pictos"><span class="emoji">🚪</span><strong>Zoek het pictogram</strong><small>Toilet, uitgang en meer.</small></button><button class="game" data-game="maps"><span class="emoji">🗺️</span><strong>Kaart of maquette?</strong><small>Kijk goed en kies.</small></button><button class="game" data-game="place"><span class="emoji">↔️</span><strong>Waar staat het kind?</strong><small>Links, rechts of tussen.</small></button><button class="game" data-game="time"><span class="emoji">⏳</span><strong>Vroeger en nu</strong><small>Herken de klas van vroeger.</small></button><button class="game" data-game="mix"><span class="emoji">⭐</span><strong>Sterrenronde</strong><small>Alles door elkaar.</small></button></section>`;document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game))}
function start(game){state.game=game;state.index=0;state.score=0;allThemes.hidden=true;gameMenu.hidden=false;if(game==='objects')state.items=sample(objects,8).map(x=>({type:'picture',pool:objects,item:x}));if(game==='pictos')state.items=shuffle(pictos).map(x=>({type:'picture',pool:pictos,item:x}));if(game==='maps')state.items=shuffle(maps).map(x=>({type:'picture',pool:maps,item:x}));if(game==='place')state.items=shuffle(['links','rechts','tussen','op']).map(x=>({type:'place',answer:x}));if(game==='time')state.items=[{type:'time',answer:'vroeger'},{type:'time',answer:'nu'}];if(game==='mix')state.items=shuffle([...sample(objects,3).map(x=>({type:'picture',pool:objects,item:x})),...sample(maps,2).map(x=>({type:'picture',pool:maps,item:x})),...sample(pictos,2).map(x=>({type:'picture',pool:pictos,item:x})),...sample(['links','rechts','tussen','op'],2).map(x=>({type:'place',answer:x})),{type:'time',answer:'vroeger'}]);render()}
function head(title){return `<div class="gamehead"><h1>${title}</h1><span class="counter">${state.index+1} / ${state.items.length}</span></div>`}
function render(){if(state.index>=state.items.length)return result();const x=state.items[state.index];if(x.type==='picture')picture(x);if(x.type==='place')place(x);if(x.type==='time')time(x)}
function title(){return {objects:'In onze klas',pictos:'Zoek het pictogram',maps:'Kaart of maquette?',place:'Waar staat het kind?',time:'Vroeger en nu',mix:'Sterrenronde'}[state.game]}
function picture(x){const options=shuffle([x.item,...sample(x.pool.filter(y=>y[0]!==x.item[0]),Math.min(3,x.pool.length-1))]);state.spoken=`Tik op de ${x.item[1]}.`;app.innerHTML=head(title())+`<section class="question"><div class="listenline"><button class="listen" aria-label="Lees voor">🔊</button><p class="prompt">Kijk en luister</p></div><div class="pictures count-${options.length}">${options.map(o=>`<button class="picture" data-right="${o[0]===x.item[0]}" aria-label="${o[1]}"><img src="assets/${o[0]}.webp" alt="${o[1]}"></button>`).join('')}</div><p class="feedback"></p></section>`;bind();setTimeout(()=>speak(),180)}
function bind(){document.querySelector('.listen').onclick=()=>speak();document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{if(document.querySelector('.correct,.wrong'))return;const right=b.dataset.right==='true';b.classList.add(right?'correct':'wrong');if(!right)document.querySelector('[data-right="true"]').classList.add('correct');if(right)state.score++;const message=right?'Goed gedaan!':'Kijk naar het groene antwoord.';document.querySelector('.feedback').innerHTML=`${message}<button class="next">Verder →</button>`;speak(message);document.querySelector('.next').onclick=()=>{state.index++;render()}})}
function place(x){state.spoken=`Waar staat het meisje? Tik op ${x.answer}.`;const scene=x.answer==='op'?`<div class="place-scene"><span class="box">📦</span><span class="kid middle" style="bottom:112px">👧</span></div>`:`<div class="place-scene"><span class="kid left">${x.answer==='links'?'👧':'🧒'}</span>${x.answer==='tussen'?'<span class="kid middle">👧</span>':''}<span class="kid right">${x.answer==='rechts'?'👧':'🧒'}</span></div>`;const choices=shuffle(x.answer==='op'?['op','naast','voor']:['links','rechts','tussen']);app.innerHTML=head(title())+`<section class="question"><div class="listenline"><button class="listen">🔊</button><p class="prompt">Waar staat het meisje?</p></div>${scene}<div class="placechoices">${choices.map(c=>`<button data-right="${c===x.answer}">${c}</button>`).join('')}</div><p class="feedback"></p></section>`;bind();setTimeout(()=>speak(),180)}
function time(x){state.spoken=`Tik op de klas van ${x.answer}.`;app.innerHTML=head(title())+`<section class="question"><div class="listenline"><button class="listen">🔊</button><p class="prompt">Klas van ${x.answer}</p></div><div class="pictures count-2"><button class="picture" data-right="${x.answer==='vroeger'}"><img src="assets/vroeger.webp" alt="Klas vroeger"></button><button class="picture" data-right="${x.answer==='nu'}"><img src="assets/nu.webp" alt="Klas nu"></button></div><p class="feedback"></p></section>`;bind();setTimeout(()=>speak(),180)}
function result(){state.spoken=`Klaar. Je had ${state.score} van de ${state.items.length} juist.`;app.innerHTML=`<section class="result"><div class="trophy">${state.score/state.items.length>=.7?'🏆':'🌟'}</div><h1>Klaar!</h1><p>${state.score} van ${state.items.length} juist</p><button id="again">Kies een ander spel</button></section>`;document.querySelector('#again').onclick=menu;speak()}
gameMenu.onclick=menu;const qrDialog=document.querySelector('#qrDialog');document.querySelector('#openQr').onclick=()=>{qrDialog.showModal();const box=document.querySelector('#qrBox');box.replaceChildren();if(window.QRCode){new QRCode(box,{text:location.href,width:220,height:220,colorDark:'#3f317f',colorLight:'#ffffff'});document.querySelector('#qrUrl').textContent=location.href}else box.textContent='De QR-code kon niet worden geladen.'};document.querySelector('#closeQr').onclick=()=>qrDialog.close();document.querySelector('#printQr').onclick=()=>window.print();menu();
