const objects=[['stoel','stoel'],['lessenaar','lessenaar'],['bureau-juf','bureau van de juf'],['bord','bord'],['boekenkast','boekenkast'],['kast','kast'],['vuilnisbak','vuilnisbak'],['penselen','penselen'],['plakband','plakband']];
const maps=[['schatkaart','schatkaart'],['plattegrond','plattegrond'],['maquette','maquette']];
const pictos=[['toilet','toilet'],['uitgang','uitgang'],['vuilnisbak','vuilnisbak']];
const articles={'stoel':'de stoel','lessenaar':'de lessenaar','bureau van de juf':'het bureau van de juf','bord':'het bord','boekenkast':'de boekenkast','kast':'de kast','vuilnisbak':'de vuilnisbak','penselen':'de penselen','plakband':'de plakband','toilet':'het toilet','uitgang':'de uitgang','schatkaart':'de schatkaart','plattegrond':'de plattegrond','maquette':'de maquette'};
const timePairs=[['klas-vroeger-realistisch','klas-nu-realistisch'],['bord-vroeger','bord-nu'],['schrijven-vroeger','schrijven-nu'],['schooltas-vroeger','schooltas-nu'],['rekenen-vroeger','rekenen-nu']];
const homes=[['flat','de flat'],['rijhuis','het rijhuis'],['vrijstaande-woning','de vrijstaande woning'],['stedelijk','stedelijk'],['landelijk','landelijk']];
const homeQuestions=[['Zoek de flat.','flat'],['Zoek het rijhuis.','rijhuis'],['Zoek de vrijstaande woning.','vrijstaande-woning'],['Zoek het stedelijk landschap.','stedelijk'],['Zoek het landelijk landschap.','landelijk']];
const wasteBins=[['glas','glas','rood'],['papier','papier en karton','geel'],['pmd','PMD','blauw'],['gft','GFT','groen'],['rest','restafval','grijs']];
const wasteItems=[['🍾','de glazen fles','glas'],['🫙','de glazen bokaal','glas'],['📰','de krant','papier'],['📦','de kartonnen doos','papier'],['🧴','de plastic fles','pmd'],['🧃','het drankkarton','pmd'],['🥫','het blikje','pmd'],['🍌','de bananenschil','gft'],['🍎','het klokhuis','gft'],['🧽','de kapotte spons','rest']];
const gridSymbols=[['ster','★'],['driehoek','▲'],['plus','✚'],['hart','♥'],['boog','◠'],['cirkel','●']];
const gridTasks=[['Zet een kruis op ster 2.',0,2],['Zet een kruis op hart 4.',3,4],['Zet een kruis op cirkel 6.',5,6],['Zet een kruis op driehoek 1.',1,1],['Zet een kruis op plus 5.',2,5],['Zet een kruis op boog 3.',4,3],['Zet een kruis op ster 6.',0,6],['Zet een kruis op cirkel 2.',5,2]];
const app=document.querySelector('#app'),speakButton=document.querySelector('#speak'),allThemes=document.querySelector('#allThemes'),gameMenu=document.querySelector('#gameMenu');
let state={game:null,index:0,score:0,items:[],spoken:''};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const sample=(a,n)=>shuffle(a).slice(0,n);
function speak(text=state.spoken){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-BE';u.rate=.82;u.pitch=1.05;window.speechSynthesis.speak(u)}
speakButton.onclick=()=>speak();
function menu(){window.speechSynthesis?.cancel();state={game:null,index:0,score:0,items:[],spoken:'Kies een spelletje.'};allThemes.hidden=false;gameMenu.hidden=true;app.innerHTML=`<section class="welcome"><div><p class="eyebrow">THEMA 1 · 1STE LEERJAAR</p><h1>Verken je klas!</h1><p>Kijk, luister en tik op de juiste prent.</p></div><img src="assets/maquette.webp" alt="Een maquette van een klas"></section><h2 class="title">Kies een spelletje</h2><section class="games"><button class="game" data-game="objects"><span class="emoji">🎒</span><strong>In onze klas</strong><small>Vind het juiste voorwerp.</small></button><button class="game" data-game="pictos"><span class="emoji">🚪</span><strong>Zoek het pictogram</strong><small>Toilet, uitgang en meer.</small></button><button class="game" data-game="maps"><span class="emoji">🗺️</span><strong>Kaart of maquette?</strong><small>Kijk goed en kies.</small></button><button class="game" data-game="grid"><span class="emoji">❎</span><strong>Vind het vakje</strong><small>Luister en tik in het rooster.</small></button><button class="game" data-game="place"><span class="emoji">↔️</span><strong>Waar staat het kind?</strong><small>Links, rechts of tussen.</small></button><button class="game" data-game="time"><span class="emoji">⏳</span><strong>Vroeger en nu</strong><small>Herken de klas van vroeger.</small></button><button class="game" data-game="homes"><span class="emoji">🏡</span><strong>Wonen en landschap</strong><small>Flat, rijhuis of vrijstaand?</small></button><button class="game" data-game="waste"><span class="emoji">♻️</span><strong>Sorteer het afval</strong><small>Sleep naar de juiste vuilbak.</small></button><button class="game" data-game="mix"><span class="emoji">⭐</span><strong>Sterrenronde</strong><small>Alles door elkaar.</small></button></section>`;document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game))}
function start(game){state.game=game;state.index=0;state.score=0;allThemes.hidden=true;gameMenu.hidden=false;if(game==='objects')state.items=sample(objects,8).map(x=>({type:'picture',pool:objects,item:x}));if(game==='pictos')state.items=shuffle(pictos).map(x=>({type:'picture',pool:pictos,item:x}));if(game==='maps')state.items=shuffle(maps).map(x=>({type:'picture',pool:maps,item:x}));if(game==='grid')state.items=shuffle(gridTasks).map(x=>({type:'grid',item:x}));if(game==='place')state.items=shuffle(['links','rechts','tussen','op']).map(x=>({type:'place',answer:x}));if(game==='time')state.items=shuffle(timePairs.flatMap(images=>['vroeger','nu'].map(answer=>({type:'time',answer,images}))));if(game==='homes')state.items=shuffle(homeQuestions).map(x=>({type:'homes',item:x}));if(game==='waste')state.items=shuffle(wasteItems).map(x=>({type:'waste',item:x}));if(game==='mix')state.items=shuffle([...sample(objects,3).map(x=>({type:'picture',pool:objects,item:x})),...sample(maps,2).map(x=>({type:'picture',pool:maps,item:x})),...sample(pictos,2).map(x=>({type:'picture',pool:pictos,item:x})),...sample(['links','rechts','tussen','op'],2).map(x=>({type:'place',answer:x})),{type:'time',answer:'vroeger',images:sample(timePairs,1)[0]}]);render()}
function head(title){return `<div class="gamehead"><h1>${title}</h1><span class="counter">${state.index+1} / ${state.items.length}</span></div>`}
function render(){if(state.index>=state.items.length)return result();const x=state.items[state.index];if(x.type==='picture')picture(x);if(x.type==='grid')gridGame(x);if(x.type==='place')place(x);if(x.type==='time')time(x);if(x.type==='homes')homeGame(x);if(x.type==='waste')wasteGame(x)}
function title(){return {objects:'In onze klas',pictos:'Zoek het pictogram',maps:'Kaart of maquette?',grid:'Vind het vakje',place:'Waar staat het kind?',time:'Vroeger en nu',homes:'Wonen en landschap',waste:'Sorteer het afval',mix:'Sterrenronde'}[state.game]}
function picture(x){const options=shuffle([x.item,...sample(x.pool.filter(y=>y[0]!==x.item[0]),Math.min(3,x.pool.length-1))]);state.spoken=`Zoek ${articles[x.item[1]]||x.item[1]}.`;app.innerHTML=head(title())+`<section class="question"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">Kijk en luister</p></div><div class="pictures count-${options.length}">${options.map(o=>`<div class="audio-option"><button class="option-listen" data-say="${articles[o[1]]||o[1]}" aria-label="Luister naar dit antwoord">🔊</button><button class="picture" data-right="${o[0]===x.item[0]}" aria-label="Kies deze afbeelding"><img src="assets/${o[0]}.webp" alt=""></button></div>`).join('')}</div><p class="feedback"></p></section>`;bind();setTimeout(()=>speak(),180)}
function bind(){const prompt=document.querySelector('.listen');if(prompt)prompt.onclick=()=>speak();document.querySelectorAll('[data-say]').forEach(b=>b.onclick=e=>{e.stopPropagation();speak(b.dataset.say)});document.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{if(document.querySelector('.correct,.wrong'))return;const right=b.dataset.right==='true';b.classList.add(right?'correct':'wrong');if(!right)document.querySelector('[data-right="true"]').classList.add('correct');if(right)state.score++;const message=right?'Goed gedaan!':'Kijk naar het groene antwoord.';document.querySelector('.feedback').innerHTML=`${message}<button class="next">Verder →</button>`;speak(message);document.querySelector('.next').onclick=()=>{state.index++;render()}})}
function gridGame(x){const [instruction,rightCol,rightRow]=x.item;state.spoken=instruction;let cells='<span class="grid-corner">↘</span>'+gridSymbols.map(s=>`<span class="grid-symbol" aria-label="${s[0]}">${s[1]}</span>`).join('');for(let row=1;row<=6;row++){cells+=`<span class="grid-number">${row}</span>`;for(let col=0;col<6;col++){const desk=row>=2&&row<=5&&col>=1&&col<=4;cells+=`<button class="grid-cell ${desk?'has-desk':''}" data-col="${col}" data-row="${row}" aria-label="${gridSymbols[col][0]} ${row}">${desk?'<span class="tiny-desk"></span>':''}</button>`}}app.innerHTML=head(title())+`<section class="question grid-question"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">Luister en tik.</p></div><p class="grid-instruction">${instruction}</p><div class="class-grid">${cells}</div><p class="feedback"></p></section>`;document.querySelector('.listen').onclick=()=>speak();let locked=false;document.querySelectorAll('.grid-cell').forEach(cell=>cell.onclick=()=>{if(locked)return;const right=Number(cell.dataset.col)===rightCol&&Number(cell.dataset.row)===rightRow;if(!right){locked=true;cell.classList.add('grid-wrong');document.querySelector('.feedback').textContent='Oei! Probeer nog eens.';speak('Oei, probeer nog eens.');setTimeout(()=>{cell.classList.remove('grid-wrong');locked=false},550);return}locked=true;cell.classList.add('grid-correct');cell.insertAdjacentHTML('beforeend','<b class="grid-cross">×</b>');state.score++;document.querySelector('.feedback').innerHTML=`Goed gevonden! <button class="next">Verder →</button>`;speak('Goed gevonden!');document.querySelector('.next').onclick=()=>{state.index++;render()}});setTimeout(()=>speak(),180)}
function place(x){state.spoken='Waar staat het meisje?';const choices=shuffle(x.answer==='op'?['op','naast','voor']:['links','rechts','tussen']);app.innerHTML=head(title())+`<section class="question place-question"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">Waar staat het meisje?</p></div><img class="place-picture" src="assets/plaats-${x.answer}.webp?v=4" alt="Een meisje en twee jongens in een klas"><div class="placechoices">${choices.map(c=>`<div class="audio-option"><button class="option-listen" data-say="${c}" aria-label="Lees ${c} voor">🔊</button><button class="choice-button" data-right="${c===x.answer}">${c}</button></div>`).join('')}</div><p class="feedback"></p></section>`;bind();setTimeout(()=>speak(),180)}
function time(x){state.spoken=`Welke afbeelding hoort bij ${x.answer}?`;const options=shuffle([['vroeger',x.images[0]],['nu',x.images[1]]]);app.innerHTML=head(title())+`<section class="question"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">Welke afbeelding hoort bij ${x.answer}?</p></div><div class="pictures count-2">${options.map(o=>`<div class="audio-option"><button class="picture classroom-picture" data-right="${o[0]===x.answer}" aria-label="Kies deze afbeelding"><img src="assets/${o[1]}.webp?v=3" alt="Afbeelding van ${o[0]}"></button></div>`).join('')}</div><p class="feedback"></p></section>`;bind();setTimeout(()=>speak(),180)}
function homeGame(x){const [question,answer]=x.item;const pool=['stedelijk','landelijk'].includes(answer)?homes.filter(h=>['stedelijk','landelijk'].includes(h[0])):homes.filter(h=>!['stedelijk','landelijk'].includes(h[0]));const options=shuffle(pool);state.spoken=question;app.innerHTML=head(title())+`<section class="question"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">${question}</p></div><div class="pictures count-${options.length} home-pictures">${options.map(o=>`<div class="audio-option"><button class="picture" data-right="${o[0]===answer}" aria-label="Kies deze afbeelding"><img src="assets/${o[0]}.webp?v=2" alt="Woning of landschap"></button></div>`).join('')}</div><p class="feedback"></p></section>`;bind();setTimeout(()=>speak(),180)}
function wasteGame(x){const [icon,name,rightBin]=x.item;state.spoken=`Sleep ${name} naar de juiste vuilbak.`;app.innerHTML=head(title())+`<section class="question waste-question"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">Waar hoort dit?</p></div><div class="l1-waste-object" id="wasteObject" draggable="true" role="button" tabindex="0"><span>${icon}</span><strong>${name}</strong><em>Sleep mij!</em></div><div class="l1-waste-bins">${wasteBins.map(b=>`<button class="l1-waste-bin bin-${b[0]}" data-bin="${b[0]}" data-right="${b[0]===rightBin}"><span class="bin-lid"></span><strong>${b[1]}</strong><small>${b[2]}</small><i data-say="${b[1]}">🔊</i></button>`).join('')}</div><p class="feedback"></p></section>`;document.querySelector('.listen').onclick=()=>speak();document.querySelectorAll('[data-say]').forEach(b=>b.onclick=e=>{e.stopPropagation();speak(b.dataset.say)});bindL1Waste()}
function bindL1Waste(){const object=document.querySelector('#wasteObject'),bins=[...document.querySelectorAll('.l1-waste-bin')];let ghost=null,moved=false,checking=false,solved=false;const choose=bin=>{if(checking||solved)return;if(bin.dataset.right!=='true'){checking=true;bin.classList.add('wrong-shake');document.querySelector('.feedback').textContent='Oei! Probeer nog eens.';speak('Oei, probeer nog eens.');setTimeout(()=>{bin.classList.remove('wrong-shake');checking=false},650);return}solved=true;bin.classList.add('correct','bin-catch');object.classList.add('sorted');state.score++;document.querySelector('.feedback').innerHTML=`Goed gesorteerd! <button class="next">Verder →</button>`;speak('Goed gesorteerd!');document.querySelector('.next').onclick=()=>{state.index++;render()}};object.ondragstart=e=>{e.dataTransfer.setData('text/plain','afval');object.classList.add('dragging')};object.ondragend=()=>object.classList.remove('dragging');bins.forEach(bin=>{bin.onclick=()=>choose(bin);bin.ondragover=e=>{e.preventDefault();bin.classList.add('drag-over')};bin.ondragleave=()=>bin.classList.remove('drag-over');bin.ondrop=e=>{e.preventDefault();bins.forEach(b=>b.classList.remove('drag-over'));choose(bin)}});object.onpointerdown=e=>{if(e.pointerType==='mouse'||solved)return;moved=false;object.setPointerCapture(e.pointerId);ghost=object.cloneNode(true);ghost.removeAttribute('id');ghost.className='l1-waste-ghost';document.body.append(ghost);ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px'};object.onpointermove=e=>{if(!ghost)return;moved=true;ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';bins.forEach(b=>b.classList.remove('drag-over'));document.elementFromPoint(e.clientX,e.clientY)?.closest('.l1-waste-bin')?.classList.add('drag-over')};object.onpointerup=e=>{if(!ghost)return;ghost.remove();ghost=null;bins.forEach(b=>b.classList.remove('drag-over'));const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.l1-waste-bin');if(moved&&target)choose(target)}}
function result(){state.spoken=`Klaar. Je had ${state.score} van de ${state.items.length} juist.`;app.innerHTML=`<section class="result"><div class="trophy">${state.score/state.items.length>=.7?'🏆':'🌟'}</div><h1>Klaar!</h1><p>${state.score} van ${state.items.length} juist</p><button id="again">Kies een ander spel</button></section>`;document.querySelector('#again').onclick=menu;speak()}
gameMenu.onclick=menu;const qrDialog=document.querySelector('#qrDialog');document.querySelector('#openQr').onclick=()=>{qrDialog.showModal();const box=document.querySelector('#qrBox');box.replaceChildren();if(window.QRCode){new QRCode(box,{text:location.href,width:220,height:220,colorDark:'#3f317f',colorLight:'#ffffff'});document.querySelector('#qrUrl').textContent=location.href}else box.textContent='De QR-code kon niet worden geladen.'};document.querySelector('#closeQr').onclick=()=>qrDialog.close();document.querySelector('#printQr').onclick=()=>window.print();menu();
