(()=>{
const pieces=[
  {id:'bord',label:'schoolbord',x:33,y:5,rx:19,ry:8},
  {id:'kring',label:'kring',x:69,y:14,rx:22,ry:13},
  {id:'banken',label:'schoolbanken',x:48,y:47,rx:24,ry:23},
  {id:'juf',label:'bureau van de juf',x:15,y:17,rx:14,ry:15},
  {id:'kasten',label:'kasten',x:78,y:48,rx:20,ry:30},
  {id:'tafels',label:'tafels',x:50,y:84,rx:33,ry:14},
  {id:'wastafel',label:'wastafel',x:94,y:84,rx:8,ry:13}
];
function furniture(p){return `<span class="furniture-shape shape-${p.id}" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span><b>${p.label}</b>`}
function addButton(){const games=document.querySelector('.games');if(!games||games.querySelector('[data-classroom-game]'))return;const button=document.createElement('button');button.className='game';button.dataset.classroomGame='';button.innerHTML='<span class="emoji">🪑</span><strong>Richt onze klas in</strong><small>Sleep de echte meubels naar hun plaats.</small>';button.onclick=open;games.insertBefore(button,games.lastElementChild)}
function open(){window.speechSynthesis?.cancel();allThemes.hidden=true;gameMenu.hidden=false;state.spoken='Sleep elk meubel ongeveer naar zijn plaats in onze lege klas.';app.innerHTML=`<div class="gamehead"><h1>Richt onze klas in</h1><span class="counter">1 / 1</span></div><section class="question classroom-layout-game"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">Sleep de meubels in de lege klas.</p></div><div class="classroom-piece-tray">${pieces.map(p=>`<button class="classroom-piece" draggable="true" data-piece="${p.id}" aria-label="${p.label}">${furniture(p)}</button>`).join('')}</div><div class="real-classroom-plan" tabindex="0" aria-label="Lege plattegrond van onze klas"><img src="assets/klasplattegrond-echt-leeg.png" alt="Lege plattegrond van onze klas"><div class="placed-furniture"></div></div><p class="feedback">Kies een meubel en sleep of tik daarna op de juiste plaats.</p></section>`;document.querySelector('.listen').onclick=()=>speak();bind();setTimeout(()=>speak(),180)}
function bind(){const tray=[...document.querySelectorAll('.classroom-piece')],plan=document.querySelector('.real-classroom-plan'),layer=document.querySelector('.placed-furniture'),feedback=document.querySelector('.feedback');let selected=null,done=0;const choose=(piece,event)=>{if(!piece||piece.classList.contains('placed'))return;const rect=plan.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*100,y=(event.clientY-rect.top)/rect.height*100,p=pieces.find(v=>v.id===piece.dataset.piece);if(Math.abs(x-p.x)>p.rx||Math.abs(y-p.y)>p.ry){plan.classList.add('wrong');feedback.textContent='Oei, daar staat dit meubel niet. Probeer nog eens.';speak('Oei, probeer nog eens.');setTimeout(()=>plan.classList.remove('wrong'),450);return}const placed=document.createElement('span');placed.className='classroom-placed';placed.style.setProperty('--x',`${p.x}%`);placed.style.setProperty('--y',`${p.y}%`);placed.innerHTML=furniture(p);layer.append(placed);piece.classList.add('placed');piece.disabled=true;selected=null;done++;feedback.textContent='Goed geplaatst!';speak('Goed geplaatst!');if(done===pieces.length){state.score=1;state.roundTotal=1;feedback.innerHTML='Alles staat goed in onze klas! <button class="next">Klaar →</button>';document.querySelector('.next').onclick=()=>result()}};tray.forEach(piece=>{piece.onclick=()=>{tray.forEach(p=>p.classList.remove('selected'));selected=piece;piece.classList.add('selected');feedback.textContent=`Tik nu ongeveer op de plaats van ${piece.querySelector('b').textContent}.`};piece.ondragstart=e=>{selected=piece;e.dataTransfer.setData('text/plain',piece.dataset.piece)}});plan.ondragover=e=>{e.preventDefault();plan.classList.add('over')};plan.ondragleave=()=>plan.classList.remove('over');plan.ondrop=e=>{e.preventDefault();plan.classList.remove('over');choose(tray.find(p=>p.dataset.piece===e.dataTransfer.getData('text/plain'))||selected,e)};plan.onclick=e=>choose(selected,e)}
new MutationObserver(addButton).observe(app,{childList:true,subtree:true});addButton();
})();
