(()=>{
const pieces=[
  {id:'bord',label:'schoolbord',icon:'▰',x:32,y:8},
  {id:'kring',label:'kring',icon:'⬒',x:68,y:13},
  {id:'banken',label:'schoolbanken',icon:'▭',x:48,y:48},
  {id:'juf',label:'bureau van de juf',icon:'▱',x:14,y:17},
  {id:'wastafel',label:'wastafel',icon:'◉',x:94,y:82}
];
function addButton(){const games=document.querySelector('.games');if(!games||games.querySelector('[data-classroom-game]'))return;const button=document.createElement('button');button.className='game';button.dataset.classroomGame='';button.innerHTML='<span class="emoji">🪑</span><strong>Richt onze klas in</strong><small>Sleep meubels naar hun plaats.</small>';button.onclick=open;games.insertBefore(button,games.lastElementChild)}
function open(){window.speechSynthesis?.cancel();allThemes.hidden=true;gameMenu.hidden=false;state.spoken='Sleep elk meubel ongeveer naar zijn plaats in onze klas.';app.innerHTML=`<div class="gamehead"><h1>Richt onze klas in</h1><span class="counter">1 / 1</span></div><section class="question classroom-layout-game"><div class="listenline"><button class="listen" aria-label="Lees de opdracht voor">🔊</button><p class="prompt">Sleep elk meubel ongeveer naar zijn plaats.</p></div><div class="classroom-piece-tray">${pieces.map(p=>`<button class="classroom-piece" draggable="true" data-piece="${p.id}"><span>${p.icon}</span><b>${p.label}</b></button>`).join('')}</div><div class="real-classroom-plan"><img src="assets/klasplattegrond-meubels-blanco.png" alt="Plattegrond van onze klas">${pieces.map(p=>`<button class="classroom-zone" data-zone="${p.id}" style="--x:${p.x}%;--y:${p.y}%" aria-label="Plaats voor ${p.label}"><span>?</span></button>`).join('')}</div><p class="feedback">Je hoeft niet exact in het midden te slepen.</p></section>`;document.querySelector('.listen').onclick=()=>speak();bind();setTimeout(()=>speak(),180)}
function bind(){const tray=[...document.querySelectorAll('.classroom-piece')],zones=[...document.querySelectorAll('.classroom-zone')],feedback=document.querySelector('.feedback');let selected=null,done=0;const place=(piece,zone)=>{if(!piece||!zone||piece.classList.contains('placed'))return;if(piece.dataset.piece!==zone.dataset.zone){zone.classList.add('wrong');feedback.textContent='Oei, probeer een andere plaats.';speak('Oei, probeer een andere plaats.');setTimeout(()=>zone.classList.remove('wrong'),500);return}zone.innerHTML=piece.innerHTML;zone.classList.add('right');piece.classList.add('placed');piece.disabled=true;done++;feedback.textContent='Goed geplaatst!';speak('Goed geplaatst!');if(done===pieces.length){state.score=1;state.roundTotal=1;feedback.innerHTML='Alles staat goed! <button class="next">Klaar →</button>';document.querySelector('.next').onclick=()=>result()}};tray.forEach(piece=>{piece.onclick=()=>{tray.forEach(p=>p.classList.remove('selected'));selected=piece;piece.classList.add('selected')};piece.ondragstart=e=>{selected=piece;e.dataTransfer.setData('text/plain',piece.dataset.piece)}});zones.forEach(zone=>{zone.onclick=()=>place(selected,zone);zone.ondragover=e=>{e.preventDefault();zone.classList.add('over')};zone.ondragleave=()=>zone.classList.remove('over');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('over');place(tray.find(p=>p.dataset.piece===e.dataTransfer.getData('text/plain'))||selected,zone)}})}
new MutationObserver(addButton).observe(app,{childList:true,subtree:true});addButton();
})();
