const base='assets/';const data=[['het bord','bord.webp'],['de kast','kast.webp'],['de boekenkast','boekenkast.webp'],['de stoel','stoel.webp'],['het bureau van de juf','bureau-juf.webp'],['de vuilnisbak','vuilnisbak.webp'],['het toilet','toilet.webp'],['de uitgang','uitgang.webp'],['de maquette','maquette.webp'],['de plattegrond','plattegrond.webp'],['links','plaats-links.webp'],['rechts','plaats-rechts.webp'],['tussen','plaats-tussen.webp'],['voor','ruimte-voor-v2.webp'],['achter','ruimte-achter-v2.webp'],['onder','ruimte-onder-v2.webp'],['naast','ruimte-naast-v2.webp'],['op','ruimte-op-v2.webp'],['vroeger','klas-vroeger-realistisch.webp'],['nu','klas-nu-realistisch.webp']];
const THEME='Verken je klas',HOME=new URL('./',location.href).href,tool=document.querySelector('#tool'),intro=document.querySelector('#intro');
function cards(){return `<section id="cards">${data.map(([word,img])=>`<article class="card"><img class="photo" src="${base+img}" alt="${word}"><h2>${word}</h2></article>`).join('')}</section>`}
function question(word,i){return [`Wijs “${word}” aan.`,`Waar zie je “${word}” in onze klas of buurt?`,`Maak mondeling een zin met “${word}”.`,`Leg in je eigen woorden uit wat “${word}” betekent.`][i%4]}
function strips(){return `<section class="strips">${data.map(([word],i)=>`<article class="strip"><b>${word}</b><span>${question(word,i)}</span></article>`).join('')}</section>`}
const HELP={'het bord':'Een groot vlak in de klas waarop de juf of meester schrijft.','de kast':'Een meubel waarin je spullen bewaart.','de boekenkast':'Een kast waarin boeken staan.','de stoel':'Een meubel waarop je zit.','het bureau van de juf':'De werktafel van de juf.','de vuilnisbak':'Een bak waarin je afval gooit.','het toilet':'De plaats waar je naar de wc gaat.','de uitgang':'De plaats waar je naar buiten gaat.','de maquette':'Een klein model van een gebouw of omgeving.','de plattegrond':'Een tekening van een ruimte van bovenaf.','links':'Aan de linkerkant.','rechts':'Aan de rechterkant.','tussen':'In het midden van twee dingen.','voor':'Aan de voorkant van iets.','achter':'Aan de achterkant van iets.','onder':'Lager dan iets anders.','naast':'Vlak aan de zijkant van iets.','op':'Bovenop iets.','vroeger':'In de tijd die voorbij is.','nu':'Op dit moment.'};
const WALL_KIND={place:new Set(['het toilet','de uitgang','links','rechts','tussen','voor','achter','onder','naast','op']),time:new Set(['vroeger','nu'])};
function wallKind(word){return Object.entries(WALL_KIND).find(([,words])=>words.has(word))?.[0]||'what'}
function wall(){return `<p class="wall-note">Formaat: 6,2 × 7,8 cm. Rood = werkwoord · geel = persoon · groen = hoe · paars = waar · oranje = wanneer · bruin = wat. Het woord wordt niet afgedrukt.</p><section class="wall-grid">${data.map(([word,img])=>`<article class="wall-card" data-kind="${wallKind(word)}"><img src="${base+img}" alt=""><div class="wall-description">${HELP[word]}</div></article>`).join('')}</section>`}
function enableCardPrintChooser(){const cards=[...document.querySelectorAll('#cards .card')];if(!cards.length)return;const bar=document.createElement('div');bar.className='card-print-tools';bar.innerHTML='<button class="choose-cards">☑ Kies wandplaten</button><span class="selection-actions" hidden><button class="choose-all">Alles kiezen</button> <button class="primary print-chosen">🖨️ Print gekozen</button> <button class="primary print-large">↔ Vergroot op liggend A4</button></span>';tool.prepend(bar);cards.forEach((card,i)=>{const label=document.createElement('label');label.className='card-choice';label.innerHTML=`<input type="checkbox" aria-label="Kies wandplaat ${i+1}"> kiezen`;card.prepend(label);label.querySelector('input').onchange=e=>card.classList.toggle('chosen',e.target.checked)});const actions=bar.querySelector('.selection-actions'),choose=bar.querySelector('.choose-cards');choose.onclick=()=>{const active=document.querySelector('#cards').classList.toggle('selecting');actions.hidden=!active;choose.textContent=active?'✕ Stop met kiezen':'☑ Kies wandplaten'};bar.querySelector('.choose-all').onclick=()=>cards.forEach(card=>{card.classList.add('chosen');card.querySelector('input').checked=true});bar.querySelector('.print-chosen').onclick=()=>printCardSelection(false);bar.querySelector('.print-large').onclick=()=>printCardSelection(true)}
function printCardSelection(large){if(!document.querySelector('#cards .card.chosen')){alert('Vink eerst minstens één wandplaat aan.');return}document.body.dataset.print=large?'card-landscape':'card-selection';if(large){const style=document.createElement('style');style.id='cardPageStyle';style.textContent='@page{size:A4 landscape;margin:10mm}';document.head.append(style)}setTimeout(()=>print(),50)}
addEventListener('afterprint',()=>{delete document.body.dataset.print;document.querySelector('#cardPageStyle')?.remove()});
function setup(){return `<section class="qr-setup"><h2>QR-kaartjes voor de kinderen</h2><label>Aantal kinderen <input id="qrCount" type="number" min="1" max="40" value="24"></label><div><button id="makeQr">Maak kaartjes</button><button id="makePoster">Maak één klasposter</button></div><p>De QR-code opent alleen de oefeningen van dit thema.</p></section><section id="qrOutput"></section>`}
function addQr(box,size){new QRCode(box,{text:HOME,width:size,height:size,colorDark:'#6552b8',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}
function qrCards(n){document.body.dataset.print='qr-cards';const o=document.querySelector('#qrOutput');o.className='qr-grid';o.innerHTML=Array.from({length:n},(_,i)=>`<article class="qr-card"><h2>Ik oefen</h2><h3>${THEME}</h3><div class="qr-code" id="qr-${i}"></div><p>Scan en oefen mee!</p></article>`).join('');document.querySelectorAll('.qr-code').forEach(x=>addQr(x,105))}
function poster(){document.body.dataset.print='qr-poster';const o=document.querySelector('#qrOutput');o.className='qr-poster-wrap';o.innerHTML=`<article class="qr-poster"><p>ZISA WO SPELEN</p><h1>Ik oefen</h1><h2>${THEME}</h2><div id="posterQr"></div><strong>Scan de QR-code en oefen mee!</strong></article>`;addQr(document.querySelector('#posterQr'),260)}
function show(v){document.body.dataset.view=v;delete document.body.dataset.print;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='cards'){intro.textContent='Wandplaten met een duidelijke foto en het grote woord.';tool.innerHTML=cards();enableCardPrintChooser()}else if(v==='strips'){intro.textContent='De leerkracht leest het strookje voor; de kinderen hoeven het woord nog niet zelf te lezen.';tool.innerHTML=strips()}else if(v==='wall'){intro.textContent='Kaartjes op maat voor de sprekende muur, zonder het woord.';tool.innerHTML=wall()}else{intro.textContent='Kies kleine QR-kaartjes voor de kinderen of één grote poster.';tool.innerHTML=setup();document.querySelector('#makeQr').onclick=()=>qrCards(Math.max(1,Math.min(40,Number(document.querySelector('#qrCount').value)||1)));document.querySelector('#makePoster').onclick=poster}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelector('#printButton').onclick=()=>print();show('cards');
