const ASSET='assets/';
const vocab=[
['de biotoop','Een plek in de natuur waar planten en dieren samenleven.','biotoop.png','where'],['eierleggend','Het dier legt eieren. De jongen komen uit een ei.','ei-kuiken.png','how'],['de fauna','Alle soorten dieren samen.','biotoop.png','what'],['de flora','Alle soorten planten samen.','plantvormen.png','what'],['de geboorte','Een jong komt ter wereld.','zoogdier.png','what'],['het huisdier','Een dier dat bij mensen woont en verzorgd wordt.','verzorgen.png','what'],['het insect','Een klein dier met zes poten en twee voelsprieten.','insect.png','what'],['het jong','Een dier dat pas geboren is.','zoogdier.png','what'],['het kruid','Een kleine plant zonder stam of takken.','plantvormen.png','what'],['het kuiken','Een jonge vogel.','ei-kuiken.png','what'],['de leefomgeving','De plek waar een mens, dier of plant woont en alles vindt wat nodig is.','biotoop.png','where'],['levendbarend','Het jong groeit in de buik van de moeder en wordt levend geboren.','zoogdier.png','how'],['de levende natuur','Planten en dieren: ze groeien, bewegen of planten zich voort.','biotoop.png','what'],['de loofboom','Een boom met bladeren die meestal afvallen in de herfst.','plantvormen.png','what'],['de naaldboom','Een boom met naalden die meestal groen blijven.','plantvormen.png','what'],['de niet-levende natuur','Water, steen, lucht en zand: dingen die niet leven.','biotoop.png','what'],['het ongedierte','Kleine dieren die schade of overlast veroorzaken.','insect.png','what'],['de proef','Een onderzoek om te kijken wat er gebeurt.','biotoop.png','what'],['de struik','Een lage plant met verschillende dunne stammen.','plantvormen.png','what'],['uitbroeden','Een dier houdt eieren warm tot de jongen uitkomen.','ei-kuiken.png','verb'],['uitkomen','Het ei gaat open en het jong verschijnt.','ei-kuiken.png','verb'],['vast','Stevig; het stroomt niet.','plantvormen.png','how'],['de vis','Een dier met vinnen dat in water leeft.','biotoop.png','what'],['verzorgen','Geven wat een mens, dier of plant nodig heeft.','verzorgen.png','verb'],['vloeibaar','Het kan stromen, zoals water en melk.','verzorgen.png','how'],['het voedsel','Wat een levend wezen eet of drinkt.','verzorgen.png','what'],['de vogel','Een dier met veren dat eieren met een harde schaal legt.','ei-kuiken.png','what'],['zogen','Een jong drinkt melk bij de moeder.','zoogdier.png','verb'],['het zoogdier','Een dier waarvan het jong melk bij de moeder drinkt.','zoogdier.png','what'],['de zuurstof','Een onzichtbare stof in de lucht die nodig is om te ademen.','biotoop.png','what']
].map(([word,definition,image,kind])=>({word,definition,image:image.replace('.png','.webp'),kind}));

vocab.find(v=>v.word==='het kuiken').image='kuiken-realistisch.png';
vocab.find(v=>v.word==='uitbroeden').image='uitbroeden-realistisch.png';
vocab.find(v=>v.word==='uitkomen').image='uitkomen-realistisch.png';

const visualMap={
'de biotoop':['vocab-sprite-1.png',0],'de fauna':['vocab-sprite-1.png',1],'de leefomgeving':['vocab-sprite-1.png',2],'de levende natuur':['vocab-sprite-1.png',3],
'de niet-levende natuur':['vocab-sprite-2.png',0],'de proef':['vocab-sprite-2.png',1],'de vis':['vocab-sprite-2.png',2],'de zuurstof':['vocab-sprite-2.png',3],
'eierleggend':['vocab-sprite-3.png',0],'de vogel':['vocab-sprite-3.png',1],'de flora':['vocab-sprite-3.png',2],'het kruid':['vocab-sprite-3.png',3],
'de loofboom':['vocab-sprite-4.png',0],'de naaldboom':['vocab-sprite-4.png',1],'de struik':['vocab-sprite-4.png',2],'vast':['vocab-sprite-4.png',3],
'de geboorte':['vocab-sprite-5.png',0],'het jong':['vocab-sprite-5.png',1],'levendbarend':['vocab-sprite-5.png',2],'zogen':['vocab-sprite-5.png',3],
'het zoogdier':['vocab-sprite-6.png',0],'het huisdier':['vocab-sprite-6.png',1],'verzorgen':['vocab-sprite-6.png',2],'vloeibaar':['vocab-sprite-6.png',3],
'het voedsel':['vocab-sprite-7.png',0],'het insect':['vocab-sprite-7.png',1],'het ongedierte':['vocab-sprite-7.png',2]
};
Object.entries(visualMap).forEach(([word,[image,panel]])=>Object.assign(vocab.find(v=>v.word===word),{image,panel}));

const sets=[
{title:'Levend of niet?',icon:'🌱',desc:'Duid aan wat leeft en wat niet leeft.',questions:[
['Wat hoort bij de levende natuur?',['de vogel','de steen','het water'],0,'biotoop.png'],['Wat hoort bij de niet-levende natuur?',['de struik','het konijn','het water'],2,'biotoop.png'],['Wat heeft een dier nodig om te ademen?',['zuurstof','zand','steen'],0,'biotoop.png']]},
{title:'Boom, struik of kruid?',icon:'🌳',desc:'Herken vier soorten planten.',questions:[
['Welke boom heeft naalden?',['de loofboom','de naaldboom','de struik'],1,'plantvormen.png'],['Welke plant heeft meer dunne stammen?',['het kruid','de struik','de loofboom'],1,'plantvormen.png'],['Welke plant blijft heel laag en heeft geen stam?',['het kruid','de naaldboom','de loofboom'],0,'plantvormen.png']]},
{title:'Allemaal beestjes',icon:'🐞',desc:'Herken insect, vis, vogel en zoogdier.',questions:[
['Welk dier heeft zes poten en voelsprieten?',['de vis','het insect','de vogel'],1,'insect.png'],['Bij welk dier drinkt het jong melk bij de moeder?',['het zoogdier','de vis','het insect'],0,'zoogdier.png'],['Welk dier heeft veren?',['de vogel','de vis','het insect'],0,'ei-kuiken.png']]},
{title:'Ei of buik?',icon:'🥚',desc:'Eierleggend, levendbarend en uitkomen.',questions:[
['Wat betekent eierleggend?',['Het jong groeit in de buik.','Het dier legt eieren.','Het dier heeft veren.'],1,'ei-kuiken.png'],['Wat betekent levendbarend?',['Het jong groeit in de buik van de moeder.','Het jong komt uit een ei.','Het dier bouwt een nest.'],0,'zoogdier.png'],['Wat gebeurt bij uitkomen?',['Het ei gaat open.','Het dier valt in slaap.','Het dier eet.'],0,'ei-kuiken.png']]},
{title:'Ik zorg voor jou',icon:'🐇',desc:'Wat heeft een huisdier nodig?',questions:[
['Wat is goed verzorgen?',['Alleen spelen.','Eten, water en een propere plek geven.','Het dier alleen laten.'],1,'verzorgen.png'],['Wat is een huisdier?',['Een dier dat bij mensen woont en verzorgd wordt.','Elk dier in het bos.','Alleen een vogel.'],0,'verzorgen.png'],['Wat is voedsel?',['Wat een levend wezen eet of drinkt.','De plek waar het woont.','De lucht rond ons.'],0,'verzorgen.png']]},
{title:'Ken je het woord?',icon:'🗣️',desc:'Kies het woord bij de uitleg.',questions:[
['Alle soorten dieren samen noemen we …',['flora','fauna','biotoop'],1,'biotoop.png'],['Alle soorten planten samen noemen we …',['flora','fauna','voedsel'],0,'plantvormen.png'],['Een plek waar planten en dieren samenleven heet …',['geboorte','biotoop','proef'],1,'biotoop.png']]}
];
let currentSet=0,currentQuestion=0,answered=false;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function show(id){speechSynthesis.cancel();$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));scrollTo(0,0)}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-BE';u.rate=.86;speechSynthesis.speak(u)}
function init(){const m=$('#exerciseMenu');sets.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML=`<span class="emoji">${s.icon}</span><strong>${s.title}</strong><small>${s.desc}</small>`;b.onclick=()=>start(i);m.append(b)});$$('[data-open]').forEach(b=>b.onclick=()=>{show(b.dataset.open);if(b.dataset.open==='teacher')renderMaterials('posters');if(b.dataset.open==='qr'){$('#qrOutput').innerHTML=''}});$$('.back-home').forEach(b=>b.onclick=()=>show('home'));$('#speakPage').onclick=()=>speak('Thema 2. Beest en bos. Kies een oefening.');$('#speakQuestion').onclick=()=>speak($('#questionText').textContent);$('#next').onclick=next;$$('[data-material]').forEach(b=>b.onclick=()=>renderMaterials(b.dataset.material));$('#selectAll').onclick=()=>toggleAll(true);$('#selectNone').onclick=()=>toggleAll(false);$('#printSelected').onclick=()=>print();$('#makeQr').onclick=()=>makeQr(false);$('#makePoster').onclick=()=>makeQr(true);$('#printQr').onclick=()=>print()}
function start(i){currentSet=i;currentQuestion=0;show('exercise');renderQuestion()}
function renderQuestion(){answered=false;const s=sets[currentSet],q=s.questions[currentQuestion];$('#progress').textContent=`${currentQuestion+1} / ${s.questions.length}`;$('#questionText').textContent=q[0];$('#questionImage').src=ASSET+q[3].replace('.png','.webp');$('#questionImage').alt=q[0];$('#feedback').textContent='';$('#next').hidden=true;const a=$('#answers');a.innerHTML='';q[1].forEach((txt,i)=>{const row=document.createElement('div');row.className='answer-option';const b=document.createElement('button');b.className='answer-choice';b.textContent=txt;b.onclick=()=>answer(b,i===q[2],q[1][q[2]]);const listen=document.createElement('button');listen.className='answer-listen';listen.type='button';listen.textContent='🔊';listen.setAttribute('aria-label',`Lees antwoord voor: ${txt}`);listen.onclick=e=>{e.stopPropagation();speak(txt)};row.append(b,listen);a.append(row)})}
function answer(btn,ok,correct){if(answered)return;answered=true;btn.classList.add(ok?'correct':'wrong');if(!ok)$$('#answers .answer-choice').find(x=>x.textContent===correct).classList.add('correct');$('#feedback').textContent=ok?'Goed zo!':'Kijk nog eens naar het groene antwoord.';speak(ok?'Goed zo!':`Het juiste antwoord is ${correct}.`);$('#next').hidden=false}
function next(){speechSynthesis.cancel();if(currentQuestion<sets[currentSet].questions.length-1){currentQuestion++;renderQuestion()}else show('home')}
function visualHtml(v){if(Number.isInteger(v.panel)){const pos=[0,33.333,66.666,100][v.panel];return `<div class="vocab-visual" style="background-image:url('${ASSET+v.image}');background-position:${pos}% 50%" role="img" aria-label="Beeld bij ${v.word}"></div>`}return `<img class="vocab-visual" src="${ASSET+v.image}" alt="Beeld bij ${v.word}">`}
function stripQuestion(v,i){const questions=v.kind==='verb'?[`Doe voor wat “${v.word}” betekent.`,`Gebruik “${v.word}” in een goede zin.`,`Geef een voorbeeld van “${v.word}”.`]:[`Wijs iets aan dat bij “${v.word}” past.`,`Gebruik “${v.word}” in een goede zin.`,`Leg in je eigen woorden uit wat “${v.word}” betekent.`,`Geef een voorbeeld van “${v.word}”.`];return questions[i%questions.length]}
function renderMaterials(type){show('teacher');$$('[data-material]').forEach(b=>b.classList.toggle('active',b.dataset.material===type));$('#selectionTools').hidden=false;const root=$('#materials');root.className=`materials materials-${type}`;root.innerHTML='';vocab.forEach((v,i)=>{const el=document.createElement('article');el.className=`material ${type==='wall'?'wall':type==='strips'?'strip':'poster'} selected`;el.dataset.kind=v.kind;let content;if(type==='wall')content=`${visualHtml(v)}<div class="wall-description">${v.definition}</div>`;else if(type==='strips')content=`<b class="strip-word">${v.word}</b><span class="strip-question">${stripQuestion(v,i)}</span><small><strong>Houvast leerkracht:</strong> ${v.definition}</small>`;else content=`${visualHtml(v)}<h3>${v.word}</h3>`;el.innerHTML=`<input type="checkbox" checked aria-label="Kies ${v.word}">${content}`;el.querySelector('input').onchange=e=>el.classList.toggle('selected',e.target.checked);root.append(el)})}
function toggleAll(on){$$('.material').forEach(x=>{x.classList.toggle('selected',on);x.querySelector('input').checked=on})}
function makeQr(poster){show('qr');const n=poster?1:Math.max(1,Math.min(40,+$('#qrCount').value||1));const url=location.href.split('#')[0];const qr=`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(url)}`;const root=$('#qrOutput');root.innerHTML='';root.classList.toggle('poster-output',poster);for(let i=0;i<n;i++){const c=document.createElement('article');c.className='qr-card'+(poster?' poster':'');c.innerHTML=poster?`<p>ZISA WO SPELEN</p><h2>Ik oefen</h2><h3>Beest en bos · 1ste leerjaar</h3><img src="${qr}" alt="QR-code naar Thema 2"><strong>Scan en oefen mee!</strong>`:`<h2>Ik oefen</h2><h3>Beest en bos · 1ste leerjaar</h3><img src="${qr}" alt="QR-code naar Thema 2"><p>Scan en oefen mee!</p>`;root.append(c)}}
init();
