const app=document.querySelector('#app');
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const picture=n=>typeof n==='number'?`assets/woord-${String(n).padStart(2,'0')}.png`:`assets/context/${n}.png`;
function questionPicture(value){const images=Array.isArray(value)?value:[value];return images.map(picture)}
function visual(q){const images=q.images||[q.image];return `<div class="question-visual ${images.length>1?'paired':''}">${images.map(src=>`<img class="photo" src="${src}" alt="Contextprent bij deze vraag">`).join('')}</div>`}
let state={},timer;
function say(text=state.spoken){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nl-BE';u.rate=.86;speechSynthesis.speak(u)}
document.querySelector('#sound').onclick=()=>say();
function nav(active){document.querySelector('#allThemes').hidden=active;document.querySelector('#exerciseMenuButton').hidden=!active}
function menu(){clearTimeout(timer);window.speechSynthesis?.cancel();state={spoken:'Kies wat je wilt oefenen over het eerste schrift.'};nav(false);app.innerHTML=`<section class="welcome"><p>2de leerjaar · thema 3</p><h1>Het eerste schrift</h1><p>Kies een oefening. Je kunt de vragen en antwoorden laten voorlezen.</p><div class="menu">${LESSONS.map((l,i)=>`<button class="mode" data-lesson="${i}"><i>${l.icon}</i><h2>Les ${l.n} · ${l.title}</h2><p>${l.n===2?"Vragen, verbinden, volgorde en een zoekplaat.":l.n===3?"Standen, de Nijl en waar of niet waar.":l.questions.length+" vragen om te oefenen."}</p></button>`).join('')}<button class="mode" id="words"><i>🖼️</i><h2>Welk woord ben ik?</h2><p>Oefen met de 36 woorden en prenten.</p></button><button class="mode" id="order"><i>🔢</i><h2>Wat gebeurde eerst?</h2><p>Zet de stappen in de juiste volgorde.</p></button><button class="mode" id="mix"><i>🌟</i><h2>Alles door elkaar</h2><p>Een mix van 15 vragen uit alle lessen.</p></button></div></section>`;app.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{const l=LESSONS[+b.dataset.lesson];if(l.n===2||l.n===3){location.href=`les${l.n}.html`;return}start(l.title,l.questions.map((q,i)=>({q:q[0],options:q.slice(1),images:questionPicture(l.questionImages[i])})))});document.querySelector('#words').onclick=()=>start('Welk woord ben ik?',shuffle(VOCABULARY).slice(0,12).map(w=>({q:w[2]+' Welk woord is dit?',options:[w[0],...shuffle(VOCABULARY.filter(x=>x!==w)).slice(0,2).map(x=>x[0])],image:w[1]})));document.querySelector('#mix').onclick=()=>start('Alles door elkaar',shuffle(LESSONS.flatMap(l=>l.questions.map((q,i)=>({q:q[0],options:q.slice(1),images:questionPicture(l.questionImages[i])})))).slice(0,15));document.querySelector('#order').onclick=()=>{state={sequence:0,step:0};nav(true);sequence()}}
function start(title,list){clearTimeout(timer);state={title,list,i:0,mistakes:[],review:false,locked:false};nav(true);render()}
function render(){if(state.i>=state.list.length){if(!state.review&&state.mistakes.length){state.list=[...state.mistakes];state.mistakes=[];state.i=0;state.review=true}else return finish()}state.locked=false;const q=state.list[state.i];state.spoken=q.q;app.innerHTML=`<div class="head"><h1>${state.title}</h1><span class="counter">${state.i+1} / ${state.list.length}${state.review?' · nog eens oefenen':''}</span></div><section class="game">${visual(q)}<div class="panel"><div class="question-row"><button class="question-sound" aria-label="Lees de vraag voor">🔊</button><p class="question">${q.q}</p></div><div class="answers">${shuffle(q.options.map((text,i)=>({text,right:i===0}))).map((o,i)=>`<div class="answer-row"><button class="answer-sound" aria-label="Lees antwoord ${i+1} voor">🔊</button><button class="answer" data-right="${o.right}" data-color="${['rood','blauw','geel'][i]}">${o.text}</button></div>`).join('')}</div><p class="feedback" role="status"></p></div></section>`;app.querySelector('.question-sound').onclick=()=>say(q.q);app.querySelectorAll('.answer-row').forEach(row=>{const b=row.querySelector('.answer');row.querySelector('.answer-sound').onclick=()=>say(b.textContent);b.onclick=()=>{if(state.locked)return;const fb=app.querySelector('.feedback');if(b.dataset.right!=='true'){if(!state.mistakes.includes(q))state.mistakes.push(q);b.classList.add('bad');fb.textContent='Nog niet. Probeer opnieuw.';say(fb.textContent);return}state.locked=true;b.classList.add('good');fb.textContent='Juist!';app.querySelectorAll('.answer').forEach(x=>x.disabled=true);say('Juist!');timer=setTimeout(()=>{state.i++;render()},900)}})}
function finish(){app.innerHTML='<section class="finish"><div style="font-size:70px">🌟</div><h1>Knap gewerkt!</h1><p>Je hebt de oefening afgerond.</p><button id="again">Kies een andere oefening</button></section>';state.spoken='Knap gewerkt! Je hebt de oefening afgerond.';document.querySelector('#again').onclick=menu;say()}
function sequence(){if(state.sequence>=SEQUENCES.length)return finish();const s=SEQUENCES[state.sequence];state.spoken=s.title+'. Kies wat eerst komt.';app.innerHTML=`<div class="head"><h1>Wat gebeurde eerst?</h1><span>${state.sequence+1} / ${SEQUENCES.length}</span></div><section class="game"><img class="photo" src="${picture(s.image)}" alt="Prent bij het onderwerp"><div><h2>${s.title}</h2><p>Klik de stappen aan van eerst naar laatst.</p><ol id="ordered"></ol><div class="sequence-choices">${shuffle(s.steps.map((text,i)=>({text,i}))).map(x=>`<button data-step="${x.i}">${x.text}</button>`).join('')}</div><p class="feedback" role="status"></p><button id="nextSequence" hidden>Volgende →</button></div></section>`;app.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const fb=app.querySelector('.feedback');say(b.textContent);if(+b.dataset.step!==state.step){fb.textContent='Welke stap komt eerder? Probeer opnieuw.';return}const li=document.createElement('li');li.textContent=b.textContent;document.querySelector('#ordered').append(li);b.disabled=true;state.step++;fb.textContent='Juist!';if(state.step===s.steps.length)document.querySelector('#nextSequence').hidden=false});document.querySelector('#nextSequence').onclick=()=>{state.sequence++;state.step=0;sequence()}}
document.querySelector('#exerciseMenuButton').onclick=menu;
const qrDialog=document.querySelector('#qrDialog');document.querySelector('#qrButton').onclick=()=>{qrDialog.showModal();const box=document.querySelector('#qrBox');box.replaceChildren();const url=new URL('./',location.href).href;if(window.QRCode&&location.protocol!=='file:'){new QRCode(box,{text:url,width:220,height:220});document.querySelector('#qrMessage').textContent=url}else box.textContent='De QR-code verschijnt wanneer de pagina online staat en de QR-bibliotheek geladen is.'};document.querySelector('#closeQr').onclick=()=>qrDialog.close();document.querySelector('#printQr').onclick=()=>window.print();
menu();

if(new URLSearchParams(location.search).get('les')==='2'){const l=LESSONS[0];start(l.title,l.questions.map((q,i)=>({q:q[0],options:q.slice(1),images:questionPicture(l.questionImages[i])})));document.querySelector('#exerciseMenuButton').onclick=()=>location.href='les2.html'}

if(new URLSearchParams(location.search).get('les')==='3'){const l=LESSONS[1];start(l.title,l.questions.map((q,i)=>({q:q[0],options:q.slice(1),images:questionPicture(l.questionImages[i])})));document.querySelector('#exerciseMenuButton').onclick=()=>location.href='les3.html'}
