(()=>{
const nav=document.querySelector('.material-menu');
const button=document.createElement('button');button.dataset.view='homework';button.textContent='📄 Huistaak maken';nav.append(button);
const source=document.createElement('a');source.href='oplossingen-thema-3.pdf';source.textContent='📘 Oplossingen werkboek';source.target='_blank';source.rel='noopener';nav.append(source);
const paper=document.createElement('section');paper.id='t3Paper';document.body.append(paper);
document.querySelector('#printButton').addEventListener('click',event=>{if(document.body.dataset.view==='homework'){event.stopImmediatePropagation();document.getElementById('hwPrint').click()}},true);
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
button.onclick=()=>{document.body.dataset.view='homework';delete document.body.dataset.print;nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));intro.textContent='Kies per les oefeningen en voeg eventueel een apart oplossingenblad toe.';tool.innerHTML=`<section class="t3-builder"><h2>Huistaak samenstellen</h2><div class="t3-fields"><label>Titel <select id="hwTitle"><option>Huistaak</option><option>Ik oefen</option><option>Ik herhaal</option></select></label><label>Nummer <input id="hwNumber" type="number" min="1" max="30" value="1"></label><label><input id="hwNumberShow" type="checkbox" checked> Nummer tonen</label></div>${LESSONS.map((l,i)=>`<fieldset><legend>Les ${l.n} · ${l.title}</legend><label><input type="checkbox" data-all="${i}"> Hele les selecteren</label><div>${[['choice','Kies het juiste antwoord'],['words','Vul in met een woordbank'],['open','Leg uit in je eigen woorden']].map(([v,t])=>`<label><input type="checkbox" data-lesson="${i}" value="${v}"> ${t}</label>`).join('')}</div></fieldset>`).join('')}<fieldset><legend>Extra oefenen</legend><label><input type="checkbox" id="hwSequence"> Zet de gebeurtenissen in volgorde</label><label><input type="checkbox" id="hwMatch"> Verbind woord en prent</label></fieldset><label><input id="hwSolutions" type="checkbox"> Apart oplossingenblad toevoegen</label><div class="t3-actions"><button id="hwPreview">Voorbeeld vernieuwen</button><button id="hwPrint">🖨️ Maak PDF / print</button></div><p id="hwStatus" role="status"></p></section>`;tool.querySelectorAll('[data-all]').forEach(b=>b.onchange=()=>{tool.querySelectorAll(`[data-lesson="${b.dataset.all}"]`).forEach(x=>x.checked=b.checked);generate()});tool.querySelectorAll('[data-lesson]').forEach(b=>b.onchange=()=>{const group=[...tool.querySelectorAll(`[data-lesson="${b.dataset.lesson}"]`)],all=tool.querySelector(`[data-all="${b.dataset.lesson}"]`);all.checked=group.every(x=>x.checked);all.indeterminate=!all.checked&&group.some(x=>x.checked);generate()});['hwTitle','hwNumber','hwNumberShow','hwSolutions','hwSequence','hwMatch'].forEach(id=>document.getElementById(id).onchange=generate);document.getElementById('hwPreview').onclick=generate;document.getElementById('hwPrint').onclick=async()=>{if(!paper.children.length&&!generate())return;const images=[...paper.querySelectorAll('img')];const loaded=await Promise.all(images.map(img=>img.decode().then(()=>true).catch(()=>false)));if(loaded.some(x=>!x)){document.getElementById('hwStatus').textContent='Een afbeelding kon niet laden. Vernieuw het voorbeeld en probeer opnieuw.';return}document.body.dataset.print='t3-homework';window.print()};generate()};
const OPEN=[
[['Waarom veranderde het leven van mensen toen ze boeren werden?','Ze bleven bij hun akkers en dieren wonen. Zo ontstonden dorpen.'],['Noem twee dingen waarvoor mensen vuur gebruikten.','Bijvoorbeeld voedsel garen, zich verwarmen, licht maken of dieren op afstand houden.']],
[['Noem drie redenen waarom de Nijl belangrijk was.','Bijvoorbeeld drinkwater, vruchtbare grond, vis, vervoer of water voor dieren.'],['Waarom weten we veel over het oude Egypte?','Er zijn voorwerpen, gebouwen en geschreven bronnen bewaard.']],
[['Leg het verschil uit tussen een dijk en een kanaal.','Een dijk houdt water tegen. Een kanaal leidt water naar een andere plaats.'],['Waarom was samenwerken nodig in Mesopotamië?','Mensen bouwden samen dijken en groeven kanalen voor de landbouw.']],
[['Hoe zorgde een goede oogst voor nieuwe beroepen?','Er was voedsel over. Niet iedereen hoefde boer te zijn en mensen konden ander werk doen.'],['Waarvoor diende de stadsmuur?','Ze beschermde de stad tegen vijanden.']],
[['Wat deed een schriftgeleerde?','Hij las, schreef en noteerde bijvoorbeeld wetten voor de koning.'],['Waarom werden ziggurats hoog gebouwd?','De mensen geloofden dat ze zo dichter bij de goden kwamen.']],
[['Waarom ontstond het schrift?','Er waren veel hoeveelheden, afspraken en regels om te onthouden. Met schrift kon men die bewaren.'],['Waarom werden belangrijke wetten in steen geschreven?','Steen blijft lang bewaard. Zo bleven belangrijke wetten bestaan.']],
[['Wat leren we uit de codex van Hammurabi?','Welke regels en wetten er toen waren.'],['Waarom werd het epos van Gilgamesj opgeschreven?','Om een verhaal over een held en goden te bewaren en door te geven.']],
[['Noem een gelijkenis tussen Egypte en Mesopotamië.','Bijvoorbeeld landbouw bij rivieren, verschillende beroepen, leiders of offers aan goden.'],['Noem een verschil tussen Egypte en Mesopotamië.','Bijvoorbeeld de Nijl tegenover de Tigris en Eufraat, of hiërogliefen tegenover spijkerschrift.']]
];
function page(title,subtitle,body,answers){return `<article class="t3-page ${answers?'t3-solutions':''}"><header><small>ZISA WO SPELEN · 2DE LEERJAAR · THEMA 3</small><h1>${title}${answers?' · oplossingen':''}</h1><h2>${subtitle}</h2>${answers?'<p>Voorbeeldantwoorden bij open vragen: andere juiste formuleringen zijn mogelijk.</p>':'<p>Naam: __________________________ Datum: ______________</p>'}</header>${body}<footer>Het eerste schrift · Eigen oefenmateriaal</footer></article>`}
function generate(){const title=document.getElementById('hwTitle').value+(document.getElementById('hwNumberShow').checked?' '+Math.max(1,Math.min(30,+document.getElementById('hwNumber').value||1)):''),plans=[...tool.querySelectorAll('[data-lesson]:checked')];let tasks=[],solutions=[];for(const x of plans){const i=+x.dataset.lesson,l=LESSONS[i],qs=l.questions.slice(0,5),type=x.value;let normal='',answer='';if(type==='choice'){const rows=qs.map(q=>({q,options:shuffle(q.slice(1))}));const render=sol=>'<h3>Kruis het juiste antwoord aan.</h3>'+rows.map(({q,options},j)=>`<div class="t3-task"><b>${j+1}. ${q[0]}</b>${options.map(o=>`<p>${sol&&o===q[1]?'☑':'☐'} ${o}</p>`).join('')}</div>`).join('');normal=render(false);answer=render(true)}else if(type==='words'){const bank=shuffle(qs.map(q=>q[1]));const render=sol=>`<h3>Vul aan. Kies uit de woordbank.</h3><p class="t3-bank">${bank.join(' · ')}</p>`+qs.map((q,j)=>`<div class="t3-task"><b>${j+1}. ${q[0]}</b><p class="t3-line">${sol?q[1]:'&nbsp;'}</p></div>`).join('');normal=render(false);answer=render(true)}else{const render=sol=>'<h3>Schrijf in je eigen woorden.</h3>'+OPEN[i].map(([q,a],j)=>`<div class="t3-task"><b>${j+1}. ${q}</b><p class="t3-writing">${sol?a:''}</p></div>`).join('');normal=render(false);answer=render(true)}const subtitle=`Les ${l.n} · ${l.title}`;tasks.push(page(title,subtitle,normal,false));solutions.push(page(title,subtitle,answer,true))}
if(document.getElementById('hwSequence').checked){const rows=SEQUENCES.map(s=>({s,steps:shuffle(s.steps)}));const render=sol=>'<h3>Nummer de stappen. Begin met 1.</h3>'+rows.map(({s,steps})=>`<div class="t3-task"><b>${s.title}</b>${steps.map(text=>`<p><span class="t3-box">${sol?s.steps.indexOf(text)+1:'&nbsp;'}</span> ${text}</p>`).join('')}</div>`).join('');tasks.push(page(title,'Wat gebeurde eerst?',render(false),false));solutions.push(page(title,'Wat gebeurde eerst?',render(true),true))}
if(document.getElementById('hwMatch').checked){const chosen=shuffle(data.filter(w=>w[0]!=='het verleden')).slice(0,4),words=shuffle(chosen);const render=sol=>'<h3>Schrijf de juiste letter bij elke prent.</h3><p class="t3-bank">'+words.map((w,i)=>`${String.fromCharCode(65+i)}. ${w[0]}`).join(' · ')+'</p><div class="t3-pictures">'+chosen.map(w=>`<div><img src="${w[1]}" alt=""><p>Letter: ${sol?String.fromCharCode(65+words.indexOf(w)):'____'}</p></div>`).join('')+'</div>';tasks.push(page(title,'Woord en prent',render(false),false));solutions.push(page(title,'Woord en prent',render(true),true))}
const solutionsOn=document.getElementById('hwSolutions').checked;paper.innerHTML=tasks.join('')+(solutionsOn?solutions.join(''):'');document.getElementById('hwStatus').textContent=tasks.length?`${tasks.length} oefenblad(en) klaar${solutionsOn?' met aparte oplossingen':''}. Bekijk hieronder het afdrukvoorbeeld.`:'Vink minstens één oefening aan.';return !!tasks.length}
})();
