const root=document.querySelector('#lesson');
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
let spoken='',round=0,groups=[],selected=null,links=[],mode='',found=new Set();
function say(t=spoken){if(!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='nl-BE';u.rate=.85;speechSynthesis.speak(u)}document.querySelector('#sound').onclick=()=>say();
const tools=[['Gewone stenen','assets/werktuigen/steen.jpg'],['Een vuistbijl van steen','assets/werktuigen/vuistbijl.jpg'],['Pijlpunten van steen of been','assets/werktuigen/pijlpunt.jpg'],['Werktuigen van brons en ijzer','assets/werktuigen/metaal.jpg']];
const causes=[['Mensen leerden gewassen verbouwen.','Ze konden op één plek blijven wonen.'],['Mensen ontdekten het vuur.','Ze konden voedsel garen en zich verwarmen.'],['Mensen zochten onderweg naar voedsel.','Ze hadden geen vaste woonplaats.'],['Mensen leerden brons en ijzer maken.','Ze konden sterkere werktuigen maken.'],['Mensen maakten betere jachtwerktuigen.','Ze konden dieren gemakkelijker vangen.']];
function menu(){mode='';root.innerHTML='<h1>De eerste mensen</h1><p>Kies een oefening bij les 2.</p><div class="menu"><button data-go="quiz">🔊 Vragen over les 2</button><button data-go="causes">🔗 Oorzaak en gevolg</button><button data-go="tools">🪨 Verbind woord en werktuig</button><button data-go="order">🔢 Wat kwam eerst?</button><button data-go="scene">🌾 Zoek op de boerderij</button></div>';spoken='Kies een oefening bij les 2.';root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>start(b.dataset.go))}
function frame(title,instruction){root.innerHTML=`<div class="top"><h1>${title}</h1><button id="back">← Les 2</button></div><p id="instruction">${instruction}</p>`;document.querySelector('#back').onclick=menu;spoken=instruction}
function footer(){root.insertAdjacentHTML('beforeend','<div class="bottom"><p id="feedback" role="status"></p><button id="next" hidden>Volgende →</button></div>')}
function start(m){mode=m;round=0;if(m==='quiz'){location.href='./?les=2';return}if(m==='scene'){found=new Set();scene();return}if(m==='order'){order();return}const pairs=m==='causes'?causes:tools;const size=innerWidth<600||innerHeight<600?2:3;groups=[];for(let i=0;i<pairs.length;i+=size)groups.push(pairs.slice(i,i+size));matching()}
function matching(){selected=null;links=[];const pairs=groups[round];frame(mode==='causes'?'Oorzaak en gevolg':'Woord en werktuig',`Ronde ${round+1} van ${groups.length}. Klik links en daarna op het passende kaartje rechts.`);root.insertAdjacentHTML('beforeend',`<div class="board"><svg aria-hidden="true"></svg><div class="column">${pairs.map((p,i)=>`<button class="card" data-left="${i}">${p[0]}</button>`).join('')}</div><div class="column">${shuffle(pairs.map((p,i)=>({p,i}))).map(({p,i})=>`<button class="card" data-right="${i}">${mode==='tools'?`<img src="${p[1]}" alt="Werktuig ${i+1}">`:p[1]}</button>`).join('')}</div></div>`);footer();root.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>{if(b.classList.contains('matched'))return;root.querySelectorAll('[data-left]').forEach(x=>x.classList.remove('selected'));selected=+b.dataset.left;b.classList.add('selected');say(b.textContent)});root.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{const fb=document.querySelector('#feedback');if(b.classList.contains('matched'))return;if(selected===null){fb.textContent='Kies eerst een kaartje links.';return}if(selected!==+b.dataset.right){fb.textContent='Deze passen nog niet. Probeer opnieuw.';say(fb.textContent);return}links.push(selected);root.querySelector(`[data-left="${selected}"]`).classList.add('matched');root.querySelector(`[data-left="${selected}"]`).classList.remove('selected');b.classList.add('matched');selected=null;draw();fb.textContent='Goed verbonden!';if(links.length===pairs.length){document.querySelector('#next').hidden=false;document.querySelector('#next').textContent=round+1===groups.length?'Klaar!':'Volgende ronde →'}});document.querySelector('#next').onclick=()=>{round++;round<groups.length?matching():complete()}}
function draw(){const board=root.querySelector('.board');if(!board)return;const rect=board.getBoundingClientRect();board.querySelector('svg').innerHTML=links.map(i=>{const l=root.querySelector(`[data-left="${i}"]`).getBoundingClientRect(),r=root.querySelector(`[data-right="${i}"]`).getBoundingClientRect();return `<line x1="${l.right-rect.left}" y1="${l.top+l.height/2-rect.top}" x2="${r.left-rect.left}" y2="${r.top+r.height/2-rect.top}" stroke="#23834c" stroke-width="4"/>`}).join('')}
addEventListener('resize',draw);
function order(){let step=0;frame('Wat kwam eerst?','Klik van het oudste naar het nieuwste werktuig.');root.insertAdjacentHTML('beforeend',`<div class="order-grid">${shuffle(tools.map((t,i)=>({t,i}))).map(({t,i})=>`<button data-order="${i}"><img src="${t[1]}" alt="${t[0]}"><span>${t[0]}</span><span class="rank">?</span></button>`).join('')}</div>`);footer();root.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{if(+b.dataset.order!==step){document.querySelector('#feedback').textContent='Er kwam nog iets eerder. Probeer opnieuw.';return}b.disabled=true;b.querySelector('.rank').textContent=++step;document.querySelector('#feedback').textContent='Juist!';if(step===4)document.querySelector('#next').hidden=false});document.querySelector('#next').onclick=complete}
const spots=[{id:'graan',kind:0,x:0,y:20,w:43,h:20},{id:'groenten',kind:0,x:54,y:21,w:46,h:21},{id:'koe',kind:1,x:6,y:40,w:30,h:28},{id:'schapen',kind:1,x:68,y:43,w:29,h:24},{id:'bijl',kind:2,x:13,y:70,w:32,h:20},{id:'sikkel',kind:2,x:58,y:72,w:27,h:18}];
function scene(){const names=['akkerbouw','veeteelt','werktuigen'];frame('Zoek op de boerderij',`Klik twee dingen aan die bij ${names[round]} horen.`);root.insertAdjacentHTML('beforeend',`<div class="scene-wrap"><div class="scene"><img src="assets/context/zoekplaat-boerderij.png" alt="Een vroeg boerendorp met gewassen, dieren en werktuigen.">${spots.map(s=>`<button class="spot ${found.has(s.id)?'found':''}" data-id="${s.id}" aria-label="${s.id}" style="left:${s.x}%;top:${s.y}%;width:${s.w}%;height:${s.h}%;--mark:${['#2278d5','#23834c','#cc3e38'][s.kind]}"></button>`).join('')}</div></div>`);footer();root.querySelectorAll('.spot').forEach(b=>b.onclick=()=>{const s=spots.find(s=>s.id===b.dataset.id);if(found.has(s.id))return;const fb=document.querySelector('#feedback');if(s.kind!==round){fb.textContent=`Zoek iets dat bij ${names[round]} hoort.`;return}found.add(s.id);b.classList.add('found');const count=spots.filter(s=>s.kind===round&&found.has(s.id)).length;fb.textContent=`Juist! ${count} van 2 gevonden.`;if(count===2){document.querySelector('#next').hidden=false;document.querySelector('#next').textContent=round===2?'Klaar!':'Volgende opdracht →'}});root.querySelector('.scene>img').onclick=()=>{document.querySelector('#feedback').textContent='Kijk naar de gewassen, dieren en werktuigen.'};document.querySelector('#next').onclick=()=>{round++;round<3?scene():complete()}}
function complete(){frame('Knap gewerkt!','Je hebt deze oefening helemaal afgerond.');root.insertAdjacentHTML('beforeend','<div class="menu"><button id="done">🌟 Kies een andere oefening van les 2</button></div>');document.querySelector('#done').onclick=menu}
menu();
