const root=document.querySelector('#lesson');let spoken='',selected=null,links=[],round=0,found=new Set();
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function say(t=spoken){if(!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='nl-BE';u.rate=.85;speechSynthesis.speak(u)}document.querySelector('#sound').onclick=()=>say();
function frame(title,text){spoken=text;root.innerHTML=`<div class="top"><h1>${title}</h1><button id="back">← Les 3</button></div><p>${text}</p>`;document.querySelector('#back').onclick=menu}
function footer(next){root.insertAdjacentHTML('beforeend','<div class="bottom"><p id="feedback" role="status"></p><button id="next" hidden>Volgende →</button></div>');document.querySelector('#next').onclick=next}
function feedback(t){document.querySelector('#feedback').textContent=t}
function complete(){frame('Knap gewerkt!','Je hebt deze oefening afgerond.');root.insertAdjacentHTML('beforeend','<div class="menu"><button id="done">🌟 Kies een andere oefening van les 3</button></div>');document.querySelector('#done').onclick=menu}
function menu(){frame('Het oude Egypte','Kies een oefening bij les 3.');root.insertAdjacentHTML('beforeend','<div class="menu"><button id="quiz">🔊 Vragen over Egypte</button><button id="groups">🔗 De standen verbinden</button><button id="nile">💧 De mindmap van de Nijl</button><button id="truth">✓ Waar of niet waar?</button></div>');document.querySelector('#quiz').onclick=()=>location.href='./?les=3';document.querySelector('#groups').onclick=groups;document.querySelector('#nile').onclick=()=>{round=0;nile()};document.querySelector('#truth').onclick=()=>{round=0;truth()}}
function groups(){selected=null;links=[];frame('De standen','Klik op een stand in de piramide en daarna op de passende groep.');root.insertAdjacentHTML('beforeend',`<div class="egypt-connect">${egyptPyramid(true)}<svg aria-hidden="true"></svg><div class="column">${shuffle(EGYPT_GROUPS.map((g,i)=>({g,i}))).map(({g,i})=>`<button class="card" data-group="${i}">${g[1]}</button>`).join('')}</div></div>`);footer(complete);root.querySelectorAll('[data-tier]').forEach(b=>b.onclick=()=>{if(links.includes(+b.dataset.tier))return;root.querySelectorAll('[data-tier]').forEach(x=>x.classList.remove('selected'));selected=+b.dataset.tier;b.classList.add('selected');say(EGYPT_GROUPS[selected][0])});root.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{if(links.includes(+b.dataset.group))return;if(selected===null)return feedback('Kies eerst een stand in de piramide.');if(selected!==+b.dataset.group)return feedback('Deze passen nog niet. Probeer opnieuw.');links.push(selected);root.querySelector(`[data-tier="${selected}"]`).classList.remove('selected');root.querySelector(`[data-tier="${selected}"]`).classList.add('matched');b.classList.add('matched');selected=null;draw();feedback('Goed verbonden!');if(links.length===5)document.querySelector('#next').hidden=false})}
function draw(){const board=root.querySelector('.egypt-connect');if(!board)return;const rect=board.getBoundingClientRect();board.querySelector('svg').innerHTML=links.map(i=>{const a=root.querySelector(`[data-tier="${i}"]`).getBoundingClientRect(),b=root.querySelector(`[data-group="${i}"]`).getBoundingClientRect();return `<line x1="${a.right-rect.left}" y1="${a.top+a.height/2-rect.top}" x2="${b.left-rect.left}" y2="${b.top+b.height/2-rect.top}" stroke="#23834c" stroke-width="3"/>`}).join('')}addEventListener('resize',draw);
function nile(){selected=null;found=new Set();const ids=round===0?[0,1,2]:[3,4,5];frame('De Nijl',`Ronde ${round+1} van 2. Klik een prentje aan. Kies dan waarom de Nijl hierbij belangrijk was.`);root.insertAdjacentHTML('beforeend',`<div class="nile-title">≋ de Nijl ≋</div><div class="nile-play"><div class="nile-slots">${ids.map(i=>`<button data-slot="${i}"><span role="img" aria-label="${NILE_USES[i][1]}">${NILE_USES[i][0]}</span><span class="slot-answer">?</span></button>`).join('')}</div><div class="nile-options">${shuffle(ids).map(i=>`<button data-use="${i}">${NILE_USES[i][2]}</button>`).join('')}</div></div>`);footer(()=>{round++;round<2?nile():complete()});root.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{if(found.has(+b.dataset.slot))return;root.querySelectorAll('[data-slot]').forEach(x=>x.classList.remove('selected'));selected=+b.dataset.slot;b.classList.add('selected');say(NILE_USES[selected][1])});root.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{if(found.has(+b.dataset.use))return;if(selected===null)return feedback('Kies eerst een prentje.');if(selected!==+b.dataset.use)return feedback('Kijk nog eens naar het prentje.');found.add(selected);const slot=root.querySelector(`[data-slot="${selected}"]`);slot.querySelector('.slot-answer').textContent=b.textContent;slot.classList.remove('selected');slot.classList.add('matched');b.disabled=true;selected=null;feedback('Juist!');if(found.size===3)document.querySelector('#next').hidden=false})}
function truth(){const f=EGYPT_FACTS[round];let answered=false;frame('Waar of niet waar?',`Zin ${round+1} van ${EGYPT_FACTS.length}. Lees of beluister de zin.`);spoken=f.text;root.insertAdjacentHTML('beforeend',`<div class="truth-game"><p class="truth-statement">${f.text}</p><div class="truth-buttons"><button data-truth="true">Waar</button><button data-truth="false">Niet waar</button></div><div class="corrections"></div></div>`);footer(()=>{round++;round<EGYPT_FACTS.length?truth():complete()});root.querySelectorAll('[data-truth]').forEach(b=>b.onclick=()=>{if(answered)return;if((b.dataset.truth==='true')!==f.right)return feedback('Denk nog eens na. Probeer opnieuw.');answered=true;b.classList.add('correct');root.querySelectorAll('[data-truth]').forEach(x=>x.disabled=true);if(f.right){feedback('Juist! Deze zin klopt.');document.querySelector('#next').hidden=false;return}feedback('Goed! Welke verbetering klopt?');root.querySelector('.corrections').innerHTML=shuffle([f.correction,f.wrong]).map(t=>`<button data-correct="${t===f.correction}">${t}</button>`).join('');root.querySelectorAll('[data-correct]').forEach(x=>x.onclick=()=>{if(x.dataset.correct!=='true')return feedback('Die verbetering klopt nog niet.');feedback('Juist verbeterd!');root.querySelectorAll('[data-correct]').forEach(y=>y.disabled=true);document.querySelector('#next').hidden=false})})}
menu();
