// Les 3: dezelfde inhoud voor spel en huistaak.
const EGYPT_GROUPS=[['de farao','de leider'],['de priesters en de schrijvers','de belangrijke mensen'],['de soldaten','de soldaten'],['de boeren, handelaars en ambachtslieden','de gewone mensen'],['de slaven en slaafgemaakten','de onvrije mensen']];
const NILE_USES=[['assets/context/nijl-drinken.png','drinken','drinkwater'],['assets/context/nijl-koken.png','koken','water om te koken'],['assets/context/nijl-grond.png','grond','vruchtbare grond'],['assets/context/nijl-vis.png','voedsel','vis om te eten'],['assets/context/nijl-boot.png','reizen','vervoer per boot'],['assets/context/nijl-dieren.png','dieren','water voor de dieren']];
const EGYPT_FACTS=[
{text:'De boeren konden ook op overstroomde akkers werken.',right:false,correction:'Bij een overstroming werkten boeren aan bouwwerken.',wrong:'Bij een overstroming had niemand ander werk.'},
{text:'De meeste mensen in het oude Egypte leefden van de jacht.',right:false,correction:'De meeste mensen waren boeren.',wrong:'De meeste mensen waren farao.'},
{text:'Schrijvers schreven hiërogliefen vaak op papyrus.',right:true},
{text:'Iedereen in het oude Egypte kon schrijven.',right:false,correction:'Slechts een kleine groep kon schrijven.',wrong:'Niemand in het oude Egypte kon schrijven.'},
{text:'Priesters hadden alleen de taak om te bidden.',right:false,correction:'Ze begeleidden ook offers en gaven de farao raad.',wrong:'Ze waren alleen bezig met kopen en verkopen.'}
];
function egyptPyramid(interactive=false){const points=['500,20 375,248 625,248','375,248 625,248 722,436 278,436','278,436 722,436 817,614 183,614','183,614 817,614 902,788 98,788','98,788 902,788 983,964 16,964'];return `<svg class="egypt-picture" viewBox="0 0 1000 1000" role="group" aria-label="Standenpiramide met vijf rijen afbeeldingen"><image href="assets/context/standenpiramide.png" width="1000" height="1000"/>${points.map((p,i)=>`<polygon class="egypt-picture-tier" ${interactive?`data-tier="${i}" role="button" tabindex="0" aria-label="Rij ${i+1}"`:''} points="${p}"/><text x="${[355,260,165,80,20][i]}" y="${[175,355,540,720,900][i]}" class="pyramid-number">${i+1}</text>`).join('')}</svg>`}
function nileMindmap(solution=false){return `<svg class="nile-clear-map" viewBox="0 0 900 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Mindmap van de Nijl. Schrijf één letter in het vakje naast elke prent."><g fill="none" stroke="#2582b1" stroke-width="3"><path d="M270 55 H330 V275 H270 M330 165 H385 M270 165 H330"/><path d="M630 55 H570 V275 H630 M515 165 H570 M630 165 H570"/></g><rect x="385" y="120" width="130" height="90" rx="16" fill="#e0f3ff" stroke="#2582b1" stroke-width="2"/><image href="assets/context/nijl-rivier.png" x="430" y="131" width="40" height="40"/><text x="450" y="195" text-anchor="middle" font-size="24" font-weight="bold" fill="#193344">de Nijl</text>${NILE_USES.map((u,i)=>{const x=i<3?30:630,y=10+(i%3)*110;return `<rect x="${x}" y="${y}" width="240" height="90" rx="12" fill="white" stroke="#b6cbd2" stroke-width="2"/><image href="${u[0]}" x="${x+(i<3?155:15)}" y="${y+10}" width="70" height="70"/><text x="${x+(i<3?65:155)}" y="${y+24}" text-anchor="middle" font-size="16" fill="#193344">letter</text><rect x="${x+(i<3?38:128)}" y="${y+32}" width="54" height="48" rx="3" fill="white" stroke="#526776" stroke-width="2"/>${solution?`<text x="${x+(i<3?65:155)}" y="${y+66}" text-anchor="middle" font-size="30" fill="#234786">${String.fromCharCode(65+i)}</text>`:''}`}).join('')}</svg>`}
function egyptHomework(type,sol){
if(type==='egyptGroups'){const order=[3,0,4,1,2];return '<h3>Verbind de standen met de juiste groep.</h3><p>Kijk naar de piramide. Verbind elk nummer met de passende groep.</p>'+egyptPyramid()+`<div class="egypt-paper-match"><div>${EGYPT_GROUPS.map((g,i)=>`<p>${i+1} <span>●</span>${sol?` <small>→ ${g[1]}</small>`:''}</p>`).join('')}</div><div>${order.map(i=>`<p>● ${EGYPT_GROUPS[i][1]}</p>`).join('')}</div></div>`}
if(type==='nileMap')return '<h3>Waarom was de Nijl belangrijk?</h3><p>Kies een antwoord uit het woordvak (A tot F). Schrijf de letter in het hokje naast de passende prent. Gebruik elke letter één keer.</p><div class="nile-bank">'+NILE_USES.map((u,i)=>`<p><b>${String.fromCharCode(65+i)}.</b> ${u[2]}</p>`).join('')+'</div>'+nileMindmap(sol)+'<h3>Denk even na.</h3><p>Noem één reden waarom jij water nodig hebt.</p><div class="t3-writing-lines">'+(sol?'<p>Bijvoorbeeld: om te drinken.</p>':'<span></span>')+'</div>';
return '<h3>Waar of niet waar?</h3><p>Omcirkel bij elke zin waar of niet waar.</p>'+EGYPT_FACTS.map((f,i)=>`<div class="egypt-fact-paper"><b>${i+1}. ${f.text}</b><div class="truth-paper"><span class="${sol&&f.right?'solution-circle':''}">waar</span><span class="${sol&&!f.right?'solution-circle':''}">niet waar</span></div></div>`).join('');
}
