const root=document.querySelector('#lesson');let spoken='',selected=null,links=[],round=0,found=new Set();
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function say(t=spoken){if(!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='nl-BE';u.rate=.85;speechSynthesis.speak(u)}document.querySelector('#sound').onclick=()=>say();
function frame(title,text){spoken=text;root.innerHTML=`<div class="top"><h1>${title}</h1><button id="back">← Les 6</button></div><p>${text}</p>`;document.querySelector('#back').onclick=menu}
function footer(next){root.insertAdjacentHTML('beforeend','<div class="bottom"><p id="feedback" role="status"></p><button id="next" hidden>Volgende →</button></div>');document.querySelector('#next').onclick=next}
function feedback(t){document.querySelector('#feedback').textContent=t}
function complete(){frame('Knap gewerkt!','Je hebt deze oefening afgerond.');root.insertAdjacentHTML('beforeend','<div class="menu"><button id="done">🌟 Kies een andere oefening van les 6</button></div>');document.querySelector('#done').onclick=menu}
function menu(){window.speechSynthesis?.cancel();frame('Leven in Mesopotamië','Kies een oefening bij les 6.');root.insertAdjacentHTML('beforeend','<div class="menu"><button id="groups">🔗 De standen verbinden</button><button id="buildings">🖼️ Ziggurat, paleis en tempel</button><button id="quiz">💬 Vragen over les 6</button></div>');document.querySelector('#groups').onclick=groups;document.querySelector('#buildings').onclick=()=>{round=0;buildings()};document.querySelector('#quiz').onclick=()=>location.href='./?les=6'}
function groups(){selected=null;links=[];frame('De standen','Klik op een stand in de piramide en daarna op de passende groep.');root.insertAdjacentHTML('beforeend',`<div class="egypt-connect">${mesoPyramid(true)}<svg class="connection-lines" aria-hidden="true"></svg><div class="column">${shuffle(MESO_GROUPS.map((g,i)=>({g,i}))).map(({g,i})=>`<button class="card" data-group="${i}">${g[1]}</button>`).join('')}</div></div>`);footer(complete);root.querySelectorAll('[data-tier]').forEach(b=>b.onclick=()=>{if(links.includes(+b.dataset.tier))return;root.querySelectorAll('[data-tier]').forEach(x=>x.classList.remove('selected'));selected=+b.dataset.tier;b.classList.add('selected');say('Rij '+(selected+1))});root.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{if(links.includes(+b.dataset.group))return;if(selected===null)return feedback('Kies eerst een stand in de piramide.');if(selected!==+b.dataset.group)return feedback('Deze passen nog niet. Probeer opnieuw.');links.push(selected);root.querySelector(`[data-tier="${selected}"]`).classList.remove('selected');root.querySelector(`[data-tier="${selected}"]`).classList.add('matched');b.classList.add('matched');selected=null;draw();feedback('Goed verbonden!');if(links.length===5)document.querySelector('#next').hidden=false})}
function draw(){const board=root.querySelector('.egypt-connect');if(!board)return;const rect=board.getBoundingClientRect();board.querySelector('.connection-lines').innerHTML=links.map(i=>{const a=root.querySelector(`[data-tier="${i}"]`).getBoundingClientRect(),b=root.querySelector(`[data-group="${i}"]`).getBoundingClientRect();return `<line x1="${a.right-rect.left}" y1="${a.top+a.height/2-rect.top}" x2="${b.left-rect.left}" y2="${b.top+b.height/2-rect.top}" stroke="#23834c" stroke-width="3"/>`}).join('')}addEventListener('resize',draw);

function buildings(){if(round===6){complete();return}const search=round<3;const q=BUILDING_QUESTIONS[search?round:round-3];frame('Gebouwen in de stad',`Opdracht ${round+1} van 6. `+(search?`Klik ${q.name} aan.`:q.question));root.insertAdjacentHTML('beforeend',search?`<div class="city-space">${mesoBuildings(true)}</div>`:`<div class="city-question"><img src="assets/context/mesopotamie-gebouwen.png" alt="Drie gebouwen in een Mesopotamische stad"><div class="city-choices">${shuffle(q.answers.map((text,i)=>({text,i}))).map(a=>`<button class="card" data-answer="${a.i}">${a.text}</button>`).join('')}</div></div>`);footer(()=>{round++;buildings()});let answered=false;
function choose(el,right){if(answered)return;if(!right){feedback('Nog niet. Kijk goed en probeer opnieuw.');return}answered=true;el.classList.add('found');feedback(search?`Juist! Dit is ${q.name}.`:'Juist!');document.querySelector('#next').hidden=false;document.querySelector('#next').textContent=round===5?'Klaar!':'Volgende →'}
root.querySelectorAll('[data-building]').forEach(el=>{const select=()=>choose(el,+el.dataset.building===round);el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}}});root.querySelector('.building-picture')?.addEventListener('click',e=>{if(!e.target.hasAttribute('data-building')&&!answered)feedback('Kijk goed naar de gebouwen en probeer opnieuw.')});root.querySelectorAll('[data-answer]').forEach(el=>el.onclick=()=>choose(el,el.dataset.answer==='0'))}
root.addEventListener('keydown',e=>{if(e.target.matches('[data-tier]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}});
menu();
