const root=document.querySelector('#lesson');let mode='recognize',round=0,selected=null,placed=[],spoken='';
function say(t=spoken){if(!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='nl-BE';u.rate=.85;speechSynthesis.speak(u)}document.querySelector('#sound').onclick=()=>say();
function frame(text){speechSynthesis?.cancel();spoken=text;root.innerHTML=`<div class="top"><h1>De tijdsband</h1><button id="back">← Kies een oefening</button></div><p id="instruction">${text}</p>`;root.querySelector('#back').onclick=menu}
function footer(next){root.insertAdjacentHTML('beforeend','<div class="bottom"><p id="feedback" role="status"></p><button id="next" hidden>Volgende →</button></div>');root.querySelector('#next').onclick=next}
function feedback(t){root.querySelector('#feedback').textContent=t}
function menu(){frame('Kies wat je wilt oefenen.');root.insertAdjacentHTML('beforeend','<div class="menu"><button id="recognize">1. Herken de periode</button><button id="place">2. Vul de tijdsband</button><button id="look">3. Kijkvragen</button></div>');root.querySelector('#recognize').onclick=()=>{round=0;recognize()};root.querySelector('#place').onclick=startPlace;root.querySelector('#look').onclick=()=>{round=0;look()}}
function recognize(){if(round===TIME_PICTURES.length){startPlace();return}const p=TIME_PICTURES[round];frame(`Prent ${round+1} van 4. Bij welke periode hoort deze prent?`);root.insertAdjacentHTML('beforeend',`<div class="time-recognize"><figure><img src="assets/context/${p.image}.png" alt="${p.caption}"><figcaption>${p.caption}<button class="caption-sound" aria-label="Lees de beschrijving voor">🔊</button></figcaption></figure><div class="time-answers">${TIME_PERIODS.map((name,i)=>`<button class="card" data-answer="${i}">${name}</button>`).join('')}</div></div>`);root.querySelector('.caption-sound').onclick=()=>say(p.caption);footer(()=>{round++;recognize()});let done=false;root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(done)return;if(+b.dataset.answer!==p.period)return feedback('Nog niet. Bekijk de prent en probeer opnieuw.');done=true;b.classList.add('matched');feedback('Juist!');root.querySelector('#next').hidden=false;root.querySelector('#next').textContent=round===3?'Naar de tijdsband →':'Volgende prent →'})}
function startPlace(){placed=[];selected=null;place()}
function place(){frame('Klik eerst op een prent en daarna op de passende balk.');root.insertAdjacentHTML('beforeend',`<div class="time-place"><div class="time-tray">${TIME_PICTURES.map((p,i)=>`<div><button class="time-picture ${placed.includes(i)?'placed':''}" data-picture="${i}" ${placed.includes(i)?'disabled':''} aria-label="Prent ${i+1}: ${p.caption}"><img src="assets/context/${p.image}.png" alt=""><span>${i+1}${placed.includes(i)?' ✓':''}</span></button><button class="caption-sound" data-read="${i}" aria-label="Lees prent ${i+1} voor">🔊</button></div>`).join('')}</div>${timeBand(placed,true)}</div>`);footer(()=>{round=0;look()});root.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>say(TIME_PICTURES[+b.dataset.read].caption));root.querySelectorAll('[data-picture]').forEach(b=>b.onclick=()=>{selected=+b.dataset.picture;root.querySelectorAll('[data-picture]').forEach(x=>x.classList.toggle('selected',x===b));feedback('Kies nu de passende balk.')});root.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{if(selected===null)return feedback('Kies eerst een prent.');if(TIME_PICTURES[selected].period!==+b.dataset.period)return feedback('Deze prent hoort bij een andere balk. Probeer opnieuw.');placed.push(selected);selected=null;place();feedback(`Juist! ${placed.length} van 4 prenten geplaatst.`);if(placed.length===4){root.querySelector('#next').hidden=false;root.querySelector('#next').textContent='Naar de kijkvragen →'}})}
function look(){if(round===TIME_QUESTIONS.length){frame('Knap gewerkt! Je hebt de tijdsband geoefend.');root.insertAdjacentHTML('beforeend','<div class="menu"><button id="done">Oefen nog eens</button></div>');root.querySelector('#done').onclick=menu;return}const q=TIME_QUESTIONS[round];frame(`Kijkvraag ${round+1} van 3. ${q[0]}`);root.insertAdjacentHTML('beforeend',`<div class="time-look">${round===2?`<div class="time-tray">${TIME_PICTURES.map((p,i)=>`<figure><img src="assets/context/${p.image}.png" alt="${p.caption}"><figcaption>Prent ${i+1}</figcaption></figure>`).join('')}</div>`:timeBand([0,1,2,3])}<div class="time-look-answers">${q[1].map((a,i)=>`<button class="card" data-answer="${i}">${a}</button>`).join('')}</div></div>`);footer(()=>{round++;look()});let done=false;root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(done)return;if(+b.dataset.answer!==q[2])return feedback('Kijk nog eens goed. Probeer opnieuw.');done=true;b.classList.add('matched');feedback('Juist!');root.querySelector('#next').hidden=false})}
menu();
